Repository Altinn/altinn-access-management-frontend, pull requests merged in 2023-04, with the labels that each got.

#280 Wrong 18next english cookie value fix
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ProfileHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Views/Home/Index.cshtml
  package.json
  src/main.jsx
  src/resources/LoadLocalizations/LoadLocalizations.tsx
  yarn.lock
Labels: bugfix

#284 Workflow to test infrastructure in At21
  .github/workflows/deploy-to-at21.yml
Labels: infrastructure

#290 Removed unused workflow and added scheduled release
  .github/release-drafter.yml
  .github/workflows/build-deploy-containerapp.yml
  .github/workflows/deploy-to-environment.yml
  .github/workflows/scheduled-release.yml
Labels: infrastructure, automation

#305 Fix for environment variable in deploy
  .github/workflows/deploy-to-at21.yml
Labels: infrastructure

#300 Setup appsettings.json environment config files
  .github/workflows/deploy-to-at21.yml
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/GeneralSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/DelegationsClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/LookupClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/ResourceRegistryClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Configuration/PlatformSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Configuration/ResourceRegistrySettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT21.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT23.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT24.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Prod.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.TT02.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.YT01.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
Labels: infrastructure

#306 add keyvault configuration
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
Labels: feature

#307 Remove double slash from FrontendBaseUrl causing "bluescreen"
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT21.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT23.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT24.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Prod.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.TT02.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.YT01.json
Labels: infrastructure

#311 Move rest of the non-sensitive configuration to appsettings
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/ClientSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/KeyVaultSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/AccessTokenProvider.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT21.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT23.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT24.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Prod.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.TT02.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.YT01.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
Labels: enhancement

#313 Update keyvaulturi in appsettings.AT23.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT23.json
Labels: infrastructure

#317 fix tag input in build-publish-deploy-to-at.yml
  .github/workflows/build-publish-deploy-to-at.yml
Labels: infrastructure

#316 Fix environment variables in deploy-to-environment.yml
  .github/workflows/deploy-to-environment.yml
Labels: infrastructure

#321 Infrastructure/debuging key vault and access token gen
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/AccessTokenProvider.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/KeyVaultService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
Labels: infrastructure

#323 Remove extra information level logging for debugging
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/AccessTokenProvider.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/KeyVaultService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
Labels: infrastructure

#326 Fix for delegable API resources not being filtered to the user selected language
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ResourceControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/ResourceController.cs
  src/rtk/features/apiDelegation/delegableApi/delegableApiSlice.ts
Labels: bugfix
