Repository Altinn/altinn-access-management-frontend, pull requests merged in 2023-10, with the labels that each got.

#572 Bugfix/568 userinfobar not supporting equal names
  src/components/UserInfoBar/UserInfoBar.module.css
  src/components/UserInfoBar/UserInfoBar.tsx
Labels: kind/bug, bugfix

#573 Add check to see if input is same as reporteeOrgNumber
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/userInfo/userInfoSlice.ts
Labels: kind/bug, bugfix

#579 Fix big icons
  src/assets/Add.svg
  src/assets/AddCircle.svg
  src/assets/Cancel.svg
  src/assets/Edit.svg
  src/assets/Error.svg
  src/assets/MinusCircle.svg
  src/assets/Office1.svg
  src/assets/RedClose.svg
  src/assets/Settings.svg
  src/assets/ShakeHands.svg
  src/components/CompactDeletableListItem/CompactDeletableListItem.tsx
  src/components/DelegationActionBar/DelegationActionBar.tsx
  src/components/DeletableListItem/DeletableListItem.tsx
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.tsx
Labels: kind/bug, bugfix

#580 Renamed Assertion method names
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/MaskinportenSchemaControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ResourceControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SingleRightCotrollerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
Labels: kind/chore

#596 URGENT: renovate package.json update
  package.json
  yarn.lock
Labels: kind/chore

#588 Make use of collectionBar prop for disabling proceed button and use small heading on small screen for pageHeader
  src/features/singleRight/components/ResourceCollectionBar/ResourceCollectionBar.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
Labels: kind/bug, bugfix

#586 Integrate check delegation access with backend
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/MaskinportenSchemaService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Altinn.AccessManagement.UI.Mocks.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/CreateDelegation/appid-506.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/3225.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/322a.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/a3-app.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/a3-app2.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/appid-502.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/appid-503.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/appid-508.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/appid-509.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/appid-510.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SingleRightClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Altinn.AccessManagement.UI.Tests.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SingleRightControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/DelegationAccessCheckResponse/3225.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/DelegationAccessCheckResponse/a3-app.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/DelegationAccessCheckResponse/appid-503.json
  src/dataObjects/dtos/singleRights/DelegationInputDto.tsx
  src/dataObjects/dtos/singleRights/ResourceIdentifierDto.tsx
  src/features/singleRight/components/ResourceActionBar/ResourceActionBar.module.css
  src/features/singleRight/components/ResourceActionBar/ResourceActionBar.tsx
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.module.css
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBar/RightsActionBar.module.css
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBar/RightsActionBar.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.module.css
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ReceiptPage/ActionBarSection/ActionBarSection.tsx
  src/features/singleRight/delegate/ReceiptPage/ReceiptPage.tsx
  src/features/singleRight/request/ChooseServicePage/ChooseServicePage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/singleRights/singleRightsSlice.ts
Labels: kind/feature-request

#600 Chore/578 move dependencies to devdep
  .github/workflows/build-frontend.yaml
  .yarn/releases/yarn-3.6.4.cjs
  .yarn/releases/yarn-4.0.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: kind/chore
