Repository Altinn/altinn-access-management-frontend, pull requests merged in 2023-11, with the labels that each got.

#606 update props on buttons
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
  src/features/apiDelegation/offered/ReceiptPage/ReceiptPage.tsx
Labels: kind/bug, bugfix

#610 Added wrapping on chip container
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/3225.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/DelegationAccessCheckResponse/3225.json
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.module.css
  src/localizations/no_nn.json
Labels: kind/bug, bugfix

#608 Handle http errors of DelegationCheck with the option of retry
  src/features/singleRight/components/ResourceActionBar/ResourceActionBar.tsx
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/request/ChooseServicePage/ChooseServicePage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/errorCodeUtils.ts
  src/rtk/features/singleRights/singleRightsSlice.ts
Labels: kind/feature-request

#623 Fixing tests after design system update
  package.json
  src/components/DeletableListItem/DeletableListItem.test.cy.tsx
  yarn.lock
Labels: kind/chore

#626 Feat/614 tries to delegate all services
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/CreateDelegation/322a.json
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.tsx
Labels: kind/bug, bugfix

#607 Bugfix/599 fixing that alert does not display right error message
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SingleRight/Details.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/3225.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/322a.json
  src/components/ErrorPanel/ErrorPanel.tsx
  src/dataObjects/dtos/singleRights/DelegationInputDto.tsx
  src/features/singleRight/components/ResourceActionBar/ResourceActionBar.tsx
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.module.css
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.tsx
  src/features/singleRight/delegate/ReceiptPage/ActionBarSection/ActionBarSection.tsx
  src/features/singleRight/delegate/ReceiptPage/ReceiptActionBarContent/ReceiptActionBarContent.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/errorCodeUtils.ts
  src/rtk/features/singleRights/singleRightsSlice.ts
Labels: kind/bug, bugfix

#627 New local list component as a wrapper for the Designsystem List
  src/components/BorderedList/BorderedList.module.css
  src/components/BorderedList/BorderedList.tsx
  src/components/BorderedList/BorderedListItem/BorderedListItem.module.css
  src/components/BorderedList/BorderedListItem/BorderedListItem.tsx
  src/components/BorderedList/index.ts
  src/components/CompactDeletableListItem/CompactDeletableListItem.module.css
  src/components/CompactDeletableListItem/CompactDeletableListItem.tsx
  src/components/DeletableListItem/DeletableListItem.test.cy.tsx
  src/components/DeletableListItem/DeletableListItem.tsx
  src/components/index.ts
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.module.css
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.module.css
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
  src/features/apiDelegation/offered/ReceiptPage/ReceiptPage.module.css
  src/features/apiDelegation/offered/ReceiptPage/ReceiptPage.tsx
  src/features/singleRight/components/SearchSection/SearchSection.tsx
Labels: kind/bug, bugfix
