Repository Altinn/altinn-access-management-frontend, pull requests merged in 2023-06, with the labels that each got.

#381 Feat/better error messages
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Views/Home/Index.cshtml
  index.html
  src/components/ErrorPanel/ErrorPanel.module.css
  src/components/ErrorPanel/ErrorPanel.tsx
  src/components/ErrorPanel/index.ts
  src/components/Filter/Filter.test.cy.tsx
  src/components/Filter/Floatover.test.cy.tsx
  src/components/Filter/OptionDisplay.test.cy.tsx
  src/components/Line/Line.tsx
  src/components/Page/PageHeader.tsx
  src/components/index.ts
  src/dataObjects/CustomError/CustomError.ts
  src/dataObjects/index.ts
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/apiDelegation/delegableApi/delegableApiSlice.ts
  src/rtk/features/apiDelegation/overviewOrg/overviewOrgSlice.ts
  src/shared/dto/DeleteOrgDto.ts
  src/shared/dto/DeleteOrgItemDto.ts
  src/shared/models/DelegableApi.ts
Labels: feature

#388 Enhancement/import digdir design tokens globally
  .gitignore
  src/components/ActionBar/ActionBar.module.css
  src/components/ActionBar/ActionBarContent.module.css
  src/components/Filter/Filter.module.css
  src/resources/css/Common.module.css
  src/resources/utils/utility.module.css
Labels: enhancement

#392 Make env differentiation between index-files
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Views/Home/Index.cshtml
  src/main.jsx
Labels: enhancement

#399 removed aria-label and added aria-hidden to filter button chevron
  src/components/Filter/FilterButton.tsx
Labels: bugfix

#410 Redesign close button
  package.json
  src/assets/RedClose.svg
  src/components/PageContainer/PageContainer.module.css
  src/components/PageContainer/PageContainer.tsx
  src/components/UserInfoBar/UserInfoBar.module.css
  src/components/UserInfoBar/UserInfoBar.tsx
  yarn.lock
Labels: feature

#418 Add resource references to the maskinporten delegation model
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/Frontend/MaskinportenSchemaDelegationFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/MaskinportenSchemaService.cs
Labels: feature

#419 Add JSdoc to ActionBarComponent
  src/components/ActionBar/ActionBar.tsx
  src/components/Filter/Filter.tsx
  src/routes/Router/Router.tsx
  src/sites/NotFoundSite/NotFoundSite.module.css
  src/sites/NotFoundSite/NotFoundSite.tsx
  src/sites/NotFoundSite/index.ts
Labels: enhancement

#417 Enhancement/415 add descriptive aria labels
  src/components/ActionBar/ActionBar.test.cy.tsx
  src/components/CompactDeletableListItem/CompactDeletableListItem.test.cy.tsx
  src/components/CompactDeletableListItem/CompactDeletableListItem.tsx
  src/components/DelegationActionBar/DelegationActionBar.test.cy.tsx
  src/components/DelegationActionBar/DelegationActionBar.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: enhancement

#416 Minor fixes on receipt page
  src/components/index.ts
  src/features/apiDelegation/components/SummaryPage/SummaryPage.module.css
  src/features/apiDelegation/components/SummaryPage/SummaryPage.tsx
  src/features/apiDelegation/components/SummaryPage/index.ts
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
  src/features/apiDelegation/offered/ReceiptPage/ReceiptPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/apiDelegation/delegationRequest/delegationRequestSlice.ts
Labels: feature

#430 Update README.md
  README.md
Labels: enhancement

#421 Feat/single rights/391 routes for singlerights
  cypress/e2e/api-delegations.cy.tsx
  src/components/PageContainer/PageContainer.tsx
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
  src/features/apiDelegation/components/SummaryPage/SummaryPage.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
  src/features/apiDelegation/offered/ReceiptPage/ReceiptPage.tsx
  src/features/singleRight/delegate/OverviewPage/OverviewPage.tsx
  src/main.jsx
  src/routes/Router/Router.tsx
  src/routes/Router/index.ts
  src/routes/paths/ApiDelegationPath.tsx
  src/routes/paths/GeneralPath.tsx
  src/routes/paths/SingleRightPath.tsx
  src/routes/paths/index.ts
Labels: feature

#432 Update README
  README.md
Labels: documentation

#441 Remove unused dependency to AccessToken
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
Labels: dependencies

#435 Update README.md
  README.md
Labels: enhancement

#447 Make pr-labeler correspond with current labels
  .github/pr-labeler.yml
  .github/release-drafter.yml
  README.md
Labels: kind/chore

#449 Update release-drafter.yml
  .github/pr-labeler.yml
  .github/release-drafter.yml
Labels: kind/chore
