Repository Altinn/altinn-access-management-frontend, pull requests merged in 2023-12, with the labels that each got.

#635 Feat/api delegation/66 bff delegation access check
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IMaskinportenSchemaClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IMaskinportenSchemaService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/MaskinportenSchemaService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/MaskinportenSchemaClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/DelegationCheck/scope-access-check/12345678.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/DelegationCheck/scope-access-check/50005545.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/MaskinportenSchemaClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/ResourceRegistryClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SingleRightClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Utils/Util.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/MaskinportenSchemaControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ResourceControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SingleRightControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/MaskinportenSchema/DelegationCheck/scope-access-schema/12345678.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/MaskinportenSchema/DelegationCheck/scope-access-schema/50005545.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/MaskinportenSchema/DelegationCheck/scope-access-schema/request.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/MaskinportenSchemaController.cs
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/feature-request

#646 Update README.md
  README.md
Labels: kind/chore

#655 .NET 8 Update
  .github/workflows/build-and-analyze-backend.yml
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Altinn.AccessManagement.UI.Core.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Altinn.AccessManagement.UI.Integration.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Altinn.AccessManagement.UI.Mocks.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Altinn.AccessManagement.UI.Tests.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.csproj
  backend/src/Altinn.AccessManagement.UI/Dockerfile
Labels: kind/feature-request

#650 Feat/single rights/636 integrate delegation with new backend endpoint
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SingleRightClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SingleRightController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT23.json
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.tsx
  src/features/singleRight/delegate/ReceiptPage/ActionBarSection/ActionBarSection.module.css
  src/features/singleRight/delegate/ReceiptPage/ReceiptActionBarContent/ReceiptActionBarContent.tsx
  src/features/singleRight/delegate/ReceiptPage/ReceiptPage.module.css
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/localizedActions.tsx
  src/rtk/features/singleRights/singleRightsSlice.ts
Labels: kind/feature-request

#664 Fix dependency renaming in github action
  .github/workflows/scheduled-release.yml
Labels: dependencies

#660 Altinn apps now only displays one action: 'Access'
  src/components/UserInfoBar/UserInfoBar.tsx
  src/dataObjects/dtos/singleRights/DelegationInputDto.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.tsx
  src/features/singleRight/delegate/ReceiptPage/ActionBarSection/ActionBarSection.tsx
  src/features/singleRight/delegate/ReceiptPage/ReceiptActionBarContent/ReceiptActionBarContent.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/singleRights/singleRightsApi.ts
  src/rtk/features/singleRights/singleRightsSlice.ts
Labels: kind/feature-request

#661 Failing resources displayed in the wrong order
  src/components/ActionBar/ActionBar.tsx
  src/features/singleRight/delegate/ReceiptPage/ActionBarSection/ActionBarSection.tsx
  src/localizations/en.json
  src/localizations/no_nn.json
Labels: kind/bug, bugfix

#662 Design Review | Changed text on Rights page
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/feature-request

#665 Feat/api delegation/634 integrate add button with delegation access check
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/DelegationCheck/scope-access-check/50067798.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/DelegationCheck/scope-access-check/50076002.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/MaskinportenSchemaControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/MaskinportenSchema/DelegationCheck/scope-access-schema/50067798.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/MaskinportenSchema/DelegationCheck/scope-access-schema/50076002.json
  src/components/DelegationActionBar/DelegationActionBar.module.css
  src/components/DelegationActionBar/DelegationActionBar.tsx
  src/components/ProgressModal/ProgressModal.tsx
  src/dataObjects/dtos/IdValuePair.tsx
  src/dataObjects/dtos/singleRights/DelegationInputDto.tsx
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/errorCodeUtils.ts
  src/rtk/features/apiDelegation/delegableApi/delegableApiSlice.ts
  src/rtk/features/singleRights/singleRightsApi.ts
  src/rtk/features/singleRights/singleRightsSlice.ts
Labels: kind/feature-request
