Repository Altinn/altinn-access-management-frontend, pull requests merged in 2023-08, with the labels that each got.

#443 Feat/single right/395 implement check delegation access mock
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/tasks.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IMaskinportenSchemaClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/HttpErrorResponse.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/BaseRight.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/DelegationInput.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/DelegationOutput.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/DelegationRequestDto.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/IdValuePair.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/RevokeOfferedDelegation.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/RevokeReceivedDelegation.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SingleRight/CheckDelegationAccess/DelegationAccessCheckResponse.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SingleRight/CheckDelegationAccess/ReasonParams.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SingleRight/CheckDelegationAccess/Role.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IMaskinportenSchemaService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISingleRightService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/MaskinportenSchemaService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SingleRightService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/MaskinportenSchemaClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/AllAccessesAppid503.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/NoAccessesAppid504.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/OnlyReadAppid505.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/ReadAndWriteAppid506.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/MaskinportenSchemaClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SingleRightClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Models/SingleRight/CheckDelegationAccess/AccessLevel.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Utils/SingleRightUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ResourceControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SingleRightCotrollerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/TestDataUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/ResourceController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SingleRightController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  src/dataObjects/dtos/CheckDelegationAccessDto.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/routes/Router/Router.tsx
Labels: kind/feature-request

#483 Feat/single services/468 new variant of actionbar
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ResourceService.cs
  src/components/ActionBar/ActionBar.module.css
  src/components/ActionBar/ActionBar.test.cy.tsx
  src/components/ActionBar/ActionBar.tsx
  src/components/ActionBar/ActionBarContent.module.css
  src/components/ActionBar/ActionBarContent.tsx
  src/components/ActionBar/ActionBarHeader.module.css
  src/components/ActionBar/ActionBarHeader.tsx
  src/components/ActionBar/ActionBarIcon.module.css
  src/components/ActionBar/ActionBarIcon.tsx
  src/components/ActionBar/Context.ts
  src/components/CollectionBar/CollectionBar.module.css
  src/components/CollectionBar/CollectionBar.tsx
  src/components/CollectionBar/index.ts
  src/components/DelegationActionBar/DelegationActionBar.tsx
  src/components/DeletableListItem/DeletableListItem.module.css
  src/components/Filter/Floatover.module.css
  src/components/Page/PageHeader.module.css
  src/components/PageContainer/PageContainer.module.css
  src/components/UserInfoBar/UserInfoBar.module.css
  src/components/index.ts
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.tsx
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.module.css
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.module.css
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.module.css
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ResourceActionBar/ResourceActionBar.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/css/Common.module.css
  src/rtk/features/singleRights/singleRightsSlice.tsx
Labels: kind/feature-request

#485 Fetching service owners from bff endpoint
  .eslintrc.cjs
  .prettierrc.cjs
  package.json
  src/components/Filter/Floatover.module.css
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/rtk/features/singleRights/singleRightsSlice.tsx
  yarn.lock
Labels: kind/feature-request

#487 Fixed text sizes with new tokens and focus boxes only visible on tab
  src/components/ActionBar/ActionBarHeader.tsx
  src/components/CollectionBar/CollectionBar.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/resources/utils/utility.module.css
  yarn.lock
Labels: kind/feature-request

#488 Quick fix of missed headingSize in ActionBar
  package.json
  src/components/ActionBar/ActionBarHeader.tsx
Labels: kind/feature-request

#489 Chore/fix lint staged
  .husky/pre-push
  .lintstagedrc.json
  cypress/e2e/.1-getting-started/todo.cy.js
  cypress/e2e/.2-advanced-examples/actions.cy.js
  cypress/e2e/.2-advanced-examples/aliasing.cy.js
  cypress/e2e/.2-advanced-examples/assertions.cy.js
  cypress/e2e/.2-advanced-examples/connectors.cy.js
  cypress/e2e/.2-advanced-examples/cookies.cy.js
  cypress/e2e/.2-advanced-examples/cypress_api.cy.js
  cypress/e2e/.2-advanced-examples/files.cy.js
  cypress/e2e/.2-advanced-examples/local_storage.cy.js
  cypress/e2e/.2-advanced-examples/location.cy.js
  cypress/e2e/.2-advanced-examples/misc.cy.js
  cypress/e2e/.2-advanced-examples/navigation.cy.js
  cypress/e2e/.2-advanced-examples/network_requests.cy.js
  cypress/e2e/.2-advanced-examples/querying.cy.js
  cypress/e2e/.2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/.2-advanced-examples/traversal.cy.js
  cypress/e2e/.2-advanced-examples/utilities.cy.js
  cypress/e2e/.2-advanced-examples/viewport.cy.js
  cypress/e2e/.2-advanced-examples/waiting.cy.js
  cypress/e2e/.2-advanced-examples/window.cy.js
  cypress/e2e/api-delegations.cy.tsx
  package.json
  src/components/ActionBar/ActionBarContent.module.css
  src/components/ActionBar/ActionBarHeader.module.css
  src/components/CollectionBar/CollectionBar.module.css
  src/components/CompactDeletableListItem/CompactDeletableListItem.module.css
  src/components/DelegationActionBar/DelegationActionBar.module.css
  src/components/DeletableListItem/DeletableListItem.module.css
  src/components/ErrorPanel/ErrorPanel.module.css
  src/components/Filter/Filter.module.css
  src/components/Filter/FilterButton.module.css
  src/components/Filter/Floatover.module.css
  src/components/Filter/OptionDisplay.module.css
  src/components/Line/Line.module.css
  src/components/NavigationButtons/NavigationButtons.module.css
  src/components/Page/PageContent.module.css
  src/components/Page/PageHeader.module.css
  src/components/PageContainer/PageContainer.module.css
  src/components/ScopeList/ScopeList.module.css
  src/components/UserInfoBar/UserInfoBar.module.css
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.module.css
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.module.css
  src/features/apiDelegation/components/SummaryPage/SummaryPage.module.css
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.module.css
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.module.css
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.module.css
  src/features/singleRight/delegate/ChooseServicePage/ResourceActionBar/ResourceActionBar.module.css
  src/resources/css/Common.module.css
  src/resources/utils/utility.module.css
  src/sites/NotFoundSite/NotFoundSite.module.css
  yarn.lock
Labels: kind/chore

#491 added new light variant to page header and shifted to using altinn token brand from DS
  src/components/Page/Context.ts
  src/components/Page/Page.tsx
  src/components/Page/PageContent.tsx
  src/components/Page/PageHeader.module.css
  src/components/Page/PageHeader.tsx
  src/components/index.ts
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
  src/features/apiDelegation/components/SummaryPage/SummaryPage.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/apiDelegation/offered/OverviewPage/OverviewPage.tsx
  src/features/apiDelegation/received/OverviewPage/OverviewPage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/css/Common.module.css
Labels: kind/feature-request

#494 Feat/single rights/468 changes requested from design review
  src/components/ActionBar/ActionBarContent.module.css
  src/components/ActionBar/ActionBarHeader.module.css
  src/components/PageContainer/PageContainer.module.css
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.module.css
Labels: kind/feature-request

#486 Feat/single rights/457 action bars reaction
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/HttpStatusException.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SingleRight/CheckDelegationAccess/DelegationAccessCheckResponse.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SingleRight/CheckDelegationAccess/Details.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SingleRight/CheckDelegationAccess/Parameters.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/ResourceRegistryClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/AllAccessesAppid503.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/NoAccessesAppid504.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/OnlyReadAppid505.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/ReadAndWriteAppid506.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SingleRightCotrollerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SingleRightController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT23.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  package.json
  src/components/CollectionBar/CollectionBar.tsx
  src/dataObjects/dtos/singleRights/ResourceIdentifierDto.tsx
  src/dataObjects/index.ts
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.module.css
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ResourceActionBar/ResourceActionBar.module.css
  src/features/singleRight/delegate/ChooseServicePage/ResourceActionBar/ResourceActionBar.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/hooks/useUpdate.tsx
  src/rtk/app/store.ts
  src/rtk/features/apiDelegation/delegableApi/delegableApiSlice.ts
  src/rtk/features/singleRights/singleRightsApi.ts
  src/rtk/features/singleRights/singleRightsSlice.ts
  yarn.lock
Labels: kind/feature-request

#496 Change useMockData value
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT21.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT24.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Prod.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.TT02.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.YT01.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/bug

#497 Fixed faulty org lookup
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/parties.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RegisterClientMock.cs
  yarn.lock
Labels: kind/bug, bugfix

#499 Forgot to rename this one thing in mock data
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/parties.json
Labels: kind/bug, bugfix

#501 Multiple small design changes
  src/components/ActionBar/ActionBarContent.module.css
  src/components/ActionBar/ActionBarHeader.module.css
  src/components/CollectionBar/CollectionBar.module.css
  src/components/CollectionBar/CollectionBar.tsx
  src/components/DeletableListItem/DeletableListItem.tsx
  src/components/Page/Context.ts
  src/components/Page/Page.tsx
  src/components/Page/index.ts
  src/components/index.ts
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.tsx
  src/features/apiDelegation/components/SummaryPage/SummaryPage.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/apiDelegation/offered/OverviewPage/OverviewPage.tsx
  src/features/apiDelegation/offered/ReceiptPage/ReceiptPage.tsx
  src/features/apiDelegation/received/OverviewPage/OverviewPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ResourceActionBar/ResourceActionBar.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/feature-request

#500 Feat/single rights/456 make progress modal
  src/components/ActionBar/ActionBar.test.cy.tsx
  src/components/Dialog/Dialog.test.cy.tsx
  src/components/Dialog/Dialog.tsx
  src/components/Dialog/DialogContent.module.css
  src/components/Dialog/DialogContent.tsx
  src/components/Dialog/DialogContext.ts
  src/components/Dialog/index.ts
  src/components/ProgressModal/ProgressModal.module.css
  src/components/ProgressModal/ProgressModal.tsx
  src/components/index.ts
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/main.jsx
  src/routes/Router/Router.tsx
  src/sites/NotFoundSite/NotFoundSite.tsx
Labels: kind/feature-request
