Repository Altinn/altinn-access-management-frontend, pull requests merged in 2023-05, with the labels that each got.

#328 Asp append version attribute for js/css asset resource files
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Views/Home/Index.cshtml
Labels: bugfix

#330 Moved cypress component tests into the folders of their respective components
  src/components/apiDelegation/reusables/OverviewPageContent/OrgDelegationAccordion/OrgDelegationAccordion.test.cy.tsx
  src/components/reusables/CompactDeletableListItem/CompactDeletableListItem.test.cy.tsx
  src/components/reusables/DeletableListItem/DeletableListItem.test.cy.tsx
  src/components/reusables/NewDelegationAccordion/NewDelegationAccordion.test.cy.tsx
Labels: enhancement

#335 Create README.md for actions
  .github/README.md
Labels: documentation

#337 Deploy to all AT environments
  .github/workflows/build-publish-deploy-to-at.yml
  .github/workflows/build-publish-deploy-via-ghcr.yml
  .github/workflows/deploy-to-at21.yml
Labels: infrastructure

#339 Update BFF for new backend MaskinportenSchema route and model
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IMaskinportenSchemaClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/BaseRight.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/Delegation.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/Frontend/MaskinportenSchemaDelegationFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/MaskinportenSchemaDelegation.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/DelegationsService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IMaskinportenSchemaService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IResourceAdministrationPoint.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/LookupService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/MaskinportenSchemaService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ProfileService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ResourceAdministrationPoint.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/MaskinportenSchemaClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/DelegationsControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/MaskinportenSchemaControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/Delegation/inbounddelegation.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/Delegation/outbounddelegation.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/MaskinportenSchema/Delegation/nav_aa_distribution/from_p50005545/to_810418672/ExpectedOutput_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/MaskinportenSchema/Delegation/nav_aa_distribution/from_p50005545/to_810418672/Input_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/MaskinportenSchema/RevokeOffered/nav_aa_distribution/from_p50004223/to_810418192/Input_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/MaskinportenSchema/RevokeReceived/nav_aa_distribution/from_810418672/to_p50004219/Input_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/MaskinportenSchema/backendOffered.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/MaskinportenSchema/backendReceived.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/MaskinportenSchema/frontendOffered.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/MaskinportenSchema/frontendReceived.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Mocks/DelegationsClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Mocks/MaskinportenSchemaClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/TestDataUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/MaskinportenSchemaController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  src/rtk/features/apiDelegation/delegationRequest/delegationRequestSlice.ts
  src/rtk/features/apiDelegation/overviewOrg/overviewOrgSlice.ts
Labels: feature

#348 Fix for new keyvault uri in AT23 on new infrastructure
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT23.json
Labels: infrastructure

#332 Feat/230 create component actionbar
  .dependencygraph/setting.json
  .vscode/extensions.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  cypress/component/reusables/index.ts
  cypress/fixtures/overviewOrgs.ts
  package.json
  src/components/apiDelegation/offered/ChooseApiPage/ChooseApiPage.module.css
  src/components/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/components/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.module.css
  src/components/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/components/apiDelegation/reusables/OverviewPageContent/OrgDelegationAccordion/OrgDelegationAccordion.module.css
  src/components/apiDelegation/reusables/OverviewPageContent/OrgDelegationAccordion/index.ts
  src/components/apiDelegation/reusables/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.module.css
  src/components/apiDelegation/reusables/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.test.cy.tsx
  src/components/apiDelegation/reusables/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.tsx
  src/components/apiDelegation/reusables/OverviewPageContent/OrgDelegationActionBar/index.ts
  src/components/apiDelegation/reusables/OverviewPageContent/OverviewPageContent.module.css
  src/components/apiDelegation/reusables/OverviewPageContent/OverviewPageContent.tsx
  src/components/reusables/ActionBar/ActionBar.module.css
  src/components/reusables/ActionBar/ActionBar.test.cy.tsx
  src/components/reusables/ActionBar/ActionBar.tsx
  src/components/reusables/ActionBar/ActionBarActions.tsx
  src/components/reusables/ActionBar/ActionBarContent.module.css
  src/components/reusables/ActionBar/ActionBarContent.tsx
  src/components/reusables/ActionBar/ActionBarIcon.module.css
  src/components/reusables/ActionBar/ActionBarIcon.tsx
  src/components/reusables/ActionBar/Context.ts
  src/components/reusables/ActionBar/index.ts
  src/components/reusables/DelegationActionBar/DelegationActionBar.module.css
  src/components/reusables/DelegationActionBar/DelegationActionBar.test.cy.tsx
  src/components/reusables/DelegationActionBar/DelegationActionBar.tsx
  src/components/reusables/DelegationActionBar/index.ts
  src/components/reusables/NewDelegationAccordion/NewDelegationAccordion.tsx
  src/components/reusables/NewDelegationAccordion/index.ts
  src/components/reusables/SummaryPage/SummaryPage.module.css
  src/components/reusables/index.ts
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/css/Common.module.css
  src/rtk/features/apiDelegation/delegableApi/delegableApiSlice.ts
  src/rtk/features/apiDelegation/overviewOrg/overviewOrgSlice.ts
  yarn.lock
Labels: feature

#357 Added health check endpoint
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Health/HealthCheckTests.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
Labels: infrastructure

#371 Added ErrorController
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/AuthenticationControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/HomeControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/MaskinportenSchemaControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ProfileControllerIntegationtest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ProfileControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/AuthenticationController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/ErrorController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/MaskinportenSchemaController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/ProfileController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
Labels: feature

#373 Feat/better error messages
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Views/Home/Index.cshtml
  src/rtk/features/apiDelegation/delegableApi/delegableApiSlice.ts
  src/rtk/features/apiDelegation/overviewOrg/overviewOrgSlice.ts
  src/rtk/features/userInfo/userInfoSlice.ts
Labels: kind/bug

#375 DataProtection
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Extensions/DataProtectionConfiguration.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
Labels: feature

#354 Feat/81 filter component
  package.json
  src/components/Filter/Filter.module.css
  src/components/Filter/Filter.test.cy.tsx
  src/components/Filter/Filter.tsx
  src/components/Filter/FilterButton.module.css
  src/components/Filter/FilterButton.tsx
  src/components/Filter/Floatover.module.css
  src/components/Filter/Floatover.test.cy.tsx
  src/components/Filter/Floatover.tsx
  src/components/Filter/OptionDisplay.module.css
  src/components/Filter/OptionDisplay.test.cy.tsx
  src/components/Filter/OptionDisplay.tsx
  src/components/Filter/index.ts
  src/components/Filter/utils.tsx
  src/components/Page/Page.module.css
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.module.css
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/css/Common.module.css
  src/resources/hooks/index.ts
  src/resources/hooks/usePrevious.tsx
  src/resources/utils/arrayUtils.test.tsx
  src/resources/utils/arrayUtils.tsx
  src/resources/utils/index.ts
  src/resources/utils/utility.module.css
  yarn.lock
Labels: kind/feature-request
