Repository Altinn/altinn-access-management-frontend, pull requests merged in 2023-09, with the labels that each got.

#517 BFF: Implement delegation endpoint
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/DelegationRequestDto.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/ResourceRegistry/Frontend/ServiceResourceFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/ResourceRegistry/ServiceResource.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISingleRightService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ResourceService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SingleRightService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/Delegation/appid-400/from_p50067798/to_810418362/ExpectedOutput_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/Delegation/appid-400/from_p50067798/to_810418532/ExpectedOutput_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/Delegation/appid-402/from_p50067798/to_810418362/ExpectedOutput_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/Delegation/appid-402/from_p50067798/to_810418532/ExpectedOutput_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/Delegation/nav_aa_distribution/from_p50005545/to_810418672/ExpectedOutput_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resources.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resourcesfe.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/CreateDelegation/3225.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/CreateDelegation/322a.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/CreateDelegation/a3-app2.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/CreateDelegation/appid-502.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/CreateDelegation/appid-503.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/CreateDelegation/appid-508.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SingleRightClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Utils/Util.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SingleRightCotrollerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/CreateDelegation/3225.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/CreateDelegation/322a.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/CreateDelegation/a3-app2.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/CreateDelegation/appid-502.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/CreateDelegation/appid-503.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/CreateDelegation/appid-508.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SingleRightController.cs
  package.json
  src/components/ActionBar/ActionBarHeader.module.css
  yarn.lock
Labels: kind/feature-request

#522 Chore: Make ChooseServicePage more readable
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ChooseServicePage/SearchSection/SearchSection.module.css
  src/features/singleRight/delegate/ChooseServicePage/SearchSection/SearchSection.tsx
Labels: kind/chore

#521 Separate RightsActionBar from ResourceActionBar
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBar/RightsActionBar.module.css
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBar/RightsActionBar.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ResourceActionBar/ResourceActionBar.tsx
Labels: kind/feature-request

#518 Feat/single rights/503 choose rights page
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/OneAccessAppid502.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/OnlyReadAppid505.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SingleRightClientMock.cs
  src/features/apiDelegation/components/SummaryPage/SummaryPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.module.css
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBar/RightsActionBar.module.css
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBar/RightsActionBar.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ResourceActionBar/ResourceActionBar.tsx
  src/features/singleRight/delegate/ChooseServicePage/SearchSection/SearchSection.module.css
  src/features/singleRight/delegate/ChooseServicePage/SearchSection/SearchSection.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/errorCodeUtils.ts
  src/rtk/app/store.ts
  src/rtk/features/singleRights/singleRightsSlice.ts
Labels: kind/feature-request

#523 Chore/remove eslint config standard
  .eslintrc.cjs
  cypress.config.ts
  package.json
  src/components/ActionBar/ActionBarContent.tsx
  src/components/ActionBar/ActionBarHeader.tsx
  src/components/Filter/Filter.test.cy.tsx
  src/components/Filter/OptionDisplay.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/rtk/features/apiDelegation/delegableApi/delegableApiSlice.ts
  src/rtk/features/apiDelegation/delegationRequest/delegationRequestSlice.ts
  yarn.lock
Labels: kind/chore

#524 add close button focus state
  src/components/PageContainer/PageContainer.module.css
  src/features/singleRight/delegate/ChooseServicePage/SearchSection/SearchSection.tsx
Labels: kind/bug, bugfix

#525 Feat/single rights/413 receipt page implement navigation
  src/features/singleRight/delegate/ReceiptPage/ReceiptPage.module.css
  src/features/singleRight/delegate/ReceiptPage/ReceiptPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/routes/Router/Router.tsx
  src/routes/paths/SingleRightPath.tsx
Labels: kind/feature-request

#548 Update ServiceResource models
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Enums/ResourcePartyType.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Enums/ResourceType.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/ResourceRegistry/ContactPoint.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/ResourceRegistry/Frontend/ServiceResourceFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/ResourceRegistry/ServiceResource.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ResourceService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resources.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resourcesfe.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
Labels: kind/feature-request, kind/chore

#555 Frontend now handles resources with missing resourceReferences
  src/rtk/features/apiDelegation/delegableApi/delegableApiSlice.ts
  src/rtk/features/apiDelegation/overviewOrg/overviewOrgSlice.ts
Labels: kind/bug, bugfix

#556 Add serialization to enum resourcePartyType
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Enums/ResourcePartyType.cs
Labels: kind/bug, bugfix

#569 make and use new component GroupElement
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  src/components/DualElementsContainer/DualElementsContainer.module.css
  src/components/DualElementsContainer/DualElementsContainer.tsx
  src/components/GroupElements/GroupElements.module.css
  src/components/GroupElements/GroupElements.tsx
  src/components/NavigationButtons/NavigationButtons.module.css
  src/components/NavigationButtons/NavigationButtons.tsx
  src/components/ProgressModal/ProgressModal.tsx
  src/components/index.ts
  src/features/apiDelegation/components/SummaryPage/SummaryPage.module.css
  src/features/apiDelegation/components/SummaryPage/SummaryPage.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ReceiptPage/ReceiptPage.module.css
  src/features/singleRight/delegate/ReceiptPage/ReceiptPage.tsx
  src/features/singleRight/request/ChooseServicePage/ChooseServicePage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/singleRights/singleRightsSlice.ts
Labels: kind/chore
