Repository Altinn/altinn-access-management-frontend, pull requests merged in 2024-12, with the labels that each got.

#1177 Chore/add nginx setup to readme
  .vscode/launch.json
  README.md
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Properties/launchSettings.json
Labels: kind/chore

#1154 Changed test data in single right delegation tests
  .github/workflows/deploy-at.yml
  playwright/config/.env.at22
  playwright/config/.env.at23
  playwright/config/.env.at24
  playwright/config/.env.tt02
  playwright/e2eTests/singleRightsDelegering.spec.ts
  playwright/fixture/pomFixture.ts
  playwright/pages/profile/delegationPage.ts
Labels: Test

#1184 Can delete access package delegation from info modal
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/AccessPackageService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IAccessPackageService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/RevokeDelegation/annleggadmin.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/RevokeDelegation/eiendom_kjop.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/packages.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/RightHolderAccess/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/AccessPackageControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/GetDelegations/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/Search/emptySearch.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/AccessPackageController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SingleRightController.cs
  src/features/amUI/userRightsPage/AccessPackageSection/ActiveDelegations.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DelegatedAreaListItem.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DeletePackageButton.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.module.css
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/DeleteResourceButton.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/accessPackageApi.ts
Labels: kind/feature-request

#1186 Made small changes to fix playwright failing tests
  playwright/pages/profile/delegationPage.ts
  playwright/playwright.config.ts
Labels: Test

#1192 Update @altinn/altinn-components to v0.10.0 and refactor related components
  .mock/mockServiceWorker.js
  package.json
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.module.css
  src/features/amUI/userRightsPage/AccessPackageSection/DelegatedAreaListItem.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DelegatedPackagesList.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessAreaListItem.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/SingleRights/ResourceSearch.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightItem.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightsSection.module.css
  src/features/amUI/users/UsersList.tsx
  yarn.lock
Labels: kind/chore
