Repository Altinn/altinn-access-management-frontend, pull requests merged in 2024-11, with the labels that each got.

#1137 Feat/amui/1101 unhappy flow ikke alle rettigheter delegert
  .mock/handlers.js
  .mock/handlers/apiDelegation.ts
  .mock/handlers/lookup.ts
  .mock/handlers/resource.ts
  .mock/handlers/singleright.ts
  .mock/handlers/user.ts
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/GetDelegations/delegations.json
  src/features/amUI/common/Snackbar/SnackbarProvider.tsx
  src/features/amUI/common/Snackbar/snackbar.module.css
  src/features/amUI/userRightsPage/DelegationModal/DelegationModalContent.tsx
  src/features/amUI/userRightsPage/DelegationModal/EditModal.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.tsx
  src/features/singleRight/delegate/ReceiptPage/ActionBarSection/ActionBarSection.stories.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/hooks/useDelegateRights.tsx
  src/rtk/features/singleRights/singleRightsApi.ts
Labels: kind/feature-request

#1144 Fixed missing scopes in API delegation overview
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/APIDelegationService.cs
  playwright/pages/loginPage.ts
Labels: kind/bug, bugfix

#1145 Using altinn-components in access-management
  .mock/mockServiceWorker.js
  .storybook/preview.tsx
  package.json
  src/features/amUI/common/Avatar/Avatar.module.css
  src/features/amUI/common/Avatar/Avatar.stories.tsx
  src/features/amUI/common/Avatar/Avatar.tsx
  src/features/amUI/common/FakePageWrapper/FakePageWrapper.module.css
  src/features/amUI/common/FakePageWrapper/FakePageWrapper.tsx
  src/features/amUI/common/FakePageWrapper/index.ts
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/features/amUI/common/PageLayoutWrapper/index.ts
  src/features/amUI/common/Snackbar/Snackbar.stories.tsx
  src/features/amUI/common/Snackbar/Snackbar.tsx
  src/features/amUI/common/Snackbar/SnackbarProvider.tsx
  src/features/amUI/common/Snackbar/index.ts
  src/features/amUI/common/Snackbar/snackbar.module.css
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceSearch.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/DeleteResourceButton.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightItem.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/features/amUI/users/UserItem/UserItem.tsx
  src/features/amUI/users/UsersPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/main.jsx
  yarn.lock
Labels: Frontend

#1155 Added endpoint for fetching accesses for use in tabs on rightholder page
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessManagement/RightHolderAccesses.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/UserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/RightHolderAccess/5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/RightHolders/RightHolderAccess/5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  src/components/UserInfoBar/UserInfoBar.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/PackageSearch.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModal.stories.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModal.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModalContent.tsx
  src/features/amUI/userRightsPage/DelegationModal/EditModal.tsx
  src/features/amUI/userRightsPage/DelegationModal/SingleRights/ResourceAlert.tsx
  src/features/amUI/userRightsPage/DelegationModal/SingleRights/ResourceInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/SingleRights/ResourceSearch.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/DeleteResourceButton.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightItem.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightsSection.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/features/amUI/users/UsersList.tsx
  src/features/amUI/users/UsersPage.tsx
  src/features/amUI/users/useFilteredRightHolders.ts
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgInfoPanel.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChosenItems.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/DelegableOrgItems.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/useOrgSearch.tsx
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.stories.tsx
  src/features/apiDelegation/offered/ConfirmationPage/DelegationLists.tsx
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/features/singleRight/request/ChooseServicePage/ChooseServicePage.tsx
  src/resources/hooks/useDelegateRights.tsx
  src/resources/hooks/useEditResource.tsx
  src/resources/hooks/useFetchRecipientInfo.tsx
  src/resources/hooks/useRevokeResource.tsx
  src/resources/utils/urnUtils.tsx
  src/rtk/app/store.ts
  src/rtk/features/lookupApi.ts
  src/rtk/features/userInfoApi.ts
Labels: kind/feature-request

#1160 Adding rigthholder to lightholders list
  src/features/amUI/users/UsersList.tsx
Labels: kind/feature-request

#1166 Update @altinn/altinn-components to v0.6.3 and adjust imports
  package.json
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/main.jsx
  yarn.lock
Labels: kind/chore

#1168 Update @altinn/altinn-components to v0.6.7
  .gitignore
  .mock/mockServiceWorker.js
  .storybook/preview.tsx
  eslint.config.cjs
  package.json
  src/features/amUI/users/UsersPage.tsx
  yarn.lock
Labels: kind/chore

#1169 Display access package delegations
  .mock/mockServiceWorker.js
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessManagement/AccessDetails.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessManagement/AccessRecipient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessManagement/Recipient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessPackage/AccessPackage.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessPackage/AccessPackageAccess.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessPackage/Frontend/AccessAreaDelegations.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessPackage/Frontend/AccessPackageDelegation.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessPackage/Frontend/AccessPackageRecipients.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/IdNamePair.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/AccessPackageService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IAccessPackageService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Altinn.AccessManagement.UI.Integration.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/ClientUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/26ca8b02-c455-4dc0-96be-f92864837ff9.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/packages.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/RightHolderAccess/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/RightHolderAccess/26ca8b02-c455-4dc0-96be-f92864837ff9.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/AccessPackageControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/GetDelegations/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/Search/emptySearch.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/emptySearch.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/AccessPackageController.cs
  src/dataObjects/dtos/IdNamePair.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.module.css
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/ActiveDelegations.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DelegatedAreaListItem.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DelegatedPackagesList.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/accessPackageApi.ts
Labels: kind/feature-request

#1170 Feat/amui/71 vise informasjon om spesifikk pakke
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/packages.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/Search/emptySearch.json
  package.json
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageInfoModal.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/ActiveDelegations.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessAreaListItem.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.module.css
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/PackageSearch.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModalContent.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModalContext.tsx
  src/features/amUI/userRightsPage/DelegationModal/EditModal.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/DeleteResourceButton.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/accessPackageApi.ts
  yarn.lock
Labels: kind/feature-request
