Repository Altinn/altinn-access-management-frontend, pull requests merged in 2024-07, with the labels that each got.

#955 move logic to bff and remove unused files
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/ApiDelegationInput.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/ApiDelegationOutput.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/DelegationOutput.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/APIDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IAPIDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/Delegation/batch-delegation-mixed-response.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/Delegation/batch-delegation-response.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/APIDelegationControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/RequestInputs/MaskinportenSchema/Delegation/Input_Batch.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/RequestInputs/MaskinportenSchema/Delegation/Input_Batch_Invalid.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/APIDelegationController.cs
  src/dataObjects/dtos/resourceDelegation.tsx
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.module.css
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.module.css
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.module.css
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
  src/features/apiDelegation/offered/ConfirmationPage/DelegationLists.tsx
  src/features/apiDelegation/offered/ReceiptPage/ReceiptPage.module.css
  src/features/apiDelegation/offered/ReceiptPage/ReceiptPage.tsx
  src/features/apiDelegation/offered/ReceiptPage/index.ts
  src/routes/Router/Router.tsx
  src/rtk/app/store.ts
  src/rtk/features/apiDelegation/apiDelegationApi.ts
  src/rtk/features/apiDelegation/delegableApi/delegableApiSlice.ts
  src/rtk/features/apiDelegation/delegationRequest/delegationRequestSlice.ts
Labels: kind/chore

#963 Add main page heading for users with power of attorney
  src/components/UserInfoBar/UserInfoBar.tsx
  src/features/amUI/users/UsersPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/app/store.ts
  src/rtk/features/userInfo/userInfoApi.ts
  src/rtk/features/userInfo/userInfoSlice.ts
Labels: kind/feature-request

#968 Replace redux-userinfo with rtq userInfoApi
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgInfoPanel.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/singleRight/request/ChooseServicePage/ChooseServicePage.tsx
  src/rtk/features/userInfo/userInfoApi.ts
Labels: kind/bug, bugfix

#953 Remove altinn-design-system package and clean up technical debt
  package.json
  src/components/ActionBar/ActionBar.test.cy.tsx
  src/components/ActionBar/ActionBarContent.module.css
  src/components/ActionBar/ActionBarHeader.module.css
  src/components/ActionBar/ActionBarHeader.tsx
  src/components/CircularProgress/CircularProgress.module.css
  src/components/CircularProgress/CircularProgress.tsx
  src/components/CircularProgress/index.ts
  src/components/CollectionBar/CollectionBar.module.css
  src/components/CollectionBar/CollectionBar.tsx
  src/components/CompactDeletableListItem/CompactDeletableListItem.module.css
  src/components/CompactDeletableListItem/CompactDeletableListItem.tsx
  src/components/ErrorPanel/ErrorPanel.tsx
  src/components/Filter/Filter.test.cy.tsx
  src/components/Filter/FilterButton.module.css
  src/components/Filter/FilterButton.tsx
  src/components/Filter/OptionDisplay.module.css
  src/components/Filter/OptionDisplay.test.cy.tsx
  src/components/Filter/OptionDisplay.tsx
  src/components/Page/PageHeader.module.css
  src/components/Page/PageHeader.tsx
  src/components/PageContainer/PageContainer.module.css
  src/components/PageContainer/PageContainer.tsx
  src/components/ProgressModal/ProgressModal.tsx
  src/components/UserInfoBar/UserInfoBar.module.css
  src/components/UserInfoBar/UserInfoBar.tsx
  src/dataObjects/index.ts
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.test.cy.tsx
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.module.css
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgInfoPanel.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.module.css
  src/features/singleRight/components/ResourceActionBar/ResourceActionBar.module.css
  src/features/singleRight/delegate/ReceiptPage/ActionBarSection/ActionBarSection.module.css
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/main.jsx
  src/resources/Token/RefreshToken.tsx
  src/resources/css/Common.module.css
  src/resources/utils/redirectUtils.ts
  src/resources/utils/utility.module.css
  src/sites/ErrorPage/ErrorPage.module.css
  src/sites/ErrorPage/contents/PageNotFound.tsx
  src/sites/ErrorPage/contents/UnknownError.tsx
  yarn.lock
Labels: kind/chore

#971 Add playwright report files to gitignore
  .gitignore
  playwright/jsonReports/jsonReport.json
Labels: kind/chore

#974 Temporary fix for eslint (using v9.0.0): disable flat config
  .eslintrc.cjs
  .vscode/settings.json
Labels: kind/chore

#969 Adding a list components to show users on the "/users" route.
  src/components/List/List.module.css
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/List/TestDataUserList.ts
  src/components/UserIcon/UserIcon.module.css
  src/components/UserIcon/UserIcon.tsx
  src/features/amUI/users/List.module.css
  src/features/amUI/users/UsersList.tsx
  src/features/amUI/users/UsersPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/feature-request

#975 Present users as a paginated list (with mocked data)
  README.md
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Enums/RegistryRoleType.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/AuthenticationHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/RightHolder.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/UserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Altinn.AccessManagement.UI.Mocks.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ReporteeList/51473841.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/51329012.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/LookupControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/RightHolders/51329012.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Test.json
  src/features/amUI/users/UsersList.module.css
  src/features/amUI/users/UsersList.tsx
  src/features/amUI/users/UsersPage.tsx
  src/resources/utils/arrayUtils.test.tsx
  src/resources/utils/arrayUtils.tsx
  src/rtk/features/userInfo/userInfoApi.ts
Labels: kind/feature-request

#978 Turn off UseMockData AT22
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
Labels: kind/chore
