Repository Altinn/altinn-access-management-frontend, pull requests merged in 2024-09, with the labels that each got.

#1055 Added issue templates for Epic, Feature, and Task
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/task.md
Labels: kind/chore

#1045 Chore/908 move overview org to rtk query
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/OrganizationApiSet.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/RevokeApiDelegationOutput.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/RevokeDelegationDto.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/RevokeOfferedDelegation.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/RevokeReceivedDelegation.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/APIDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IAPIDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/frontendCovered_OverviewOrg.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/frontendOffered_OverviewOrg.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/APIDelegationControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/RequestInputs/MaskinportenSchema/RevokeOffered/Input_revoke_delegation_batch_dto.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/RequestInputs/MaskinportenSchema/RevokeOffered/Input_revoke_delegation_batch_dto_partial_success.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/RequestInputs/MaskinportenSchema/RevokeOffered/Input_revoke_delegation_dto.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/RequestInputs/MaskinportenSchema/RevokeReceived/Input_revoke_delegation_batch_dto.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/RequestInputs/MaskinportenSchema/RevokeReceived/Input_revoke_delegation_batch_dto_partial_success.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/RequestInputs/MaskinportenSchema/RevokeReceived/Input_revoke_delegation_dto.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/APIDelegationController.cs
  src/components/DeletableListItem/DeletableListItem.test.cy.tsx
  src/components/DeletableListItem/DeletableListItem.tsx
  src/features/apiDelegation/components/DelegationType.tsx
  src/features/apiDelegation/components/LayoutState.tsx
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.test.cy.tsx
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.tsx
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
  src/features/apiDelegation/components/OverviewPageContent/useSoftDeleteApi.ts
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
  src/features/apiDelegation/offered/OverviewPage/OverviewPage.tsx
  src/features/apiDelegation/received/OverviewPage/OverviewPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/main.jsx
  src/rtk/app/store.ts
  src/rtk/features/apiDelegation/apiDelegationApi.ts
  src/rtk/features/apiDelegation/overviewOrg/overviewOrgApi.ts
  src/rtk/features/apiDelegation/overviewOrg/overviewOrgSlice.ts
Labels: kind/chore

#1057 fix api select for deletion bug
  src/features/apiDelegation/components/OverviewPageContent/useSoftDeleteApi.ts
Labels: kind/bug, bugfix

#1056 Added bug and testplan templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/testplan.md
Labels: kind/chore

#1059 Invalidate cach on post api-delegation
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
Labels: kind/bug, bugfix

#1060 Fix so that overview refetches after new delegations
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
Labels: kind/bug, bugfix

#1053 Run BFF tests on PRs
  .github/workflows/template-build-and-test-backend.yml
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/APIDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/AuthenticationControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/HomeControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/MaskinportenSchema/frontendOffered.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/MaskinportenSchema/frontendReceived.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/TestDataUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
Labels: kind/bug, bugfix

#1052 Display popular services on SingleRights
  .yarn/releases/yarn-4.4.1.cjs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/FeatureFlags.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ResourceService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Views/Home/Index.cshtml
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Prod.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.TT02.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/global.d.ts
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  tsconfig.json
Labels: kind/feature-request

#1063 Fix: Display orgnumber on API overview
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.test.cy.tsx
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.tsx
Labels: kind/bug, bugfix

#1062 Feat/move cypress tests/1023
  .github/workflows/deploy-at.yml
  .yarn/releases/yarn-4.4.1.cjs
  playwright/README.md
  playwright/e2eTests/api-delegering.spec.ts
  playwright/e2eTests/idPortenLogin.spec.ts
  playwright/e2eTests/singleRightsDelegering.spec.ts
  playwright/fixture/pomFixture.ts
  playwright/jsonReports/jsonReport.json
  playwright/pages/loginPage.ts
  playwright/pages/profile/apidelegeringPage.ts
  playwright/pages/profile/delegationPage.ts
  playwright/playwright.config.ts
Labels: kind/feature-request

#1074 Add new resource types to ResourceType enum
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Enums/ResourceType.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/appsettings.test.json
Labels: kind/chore

#1073 resource search includes hits on "keywords" data
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/ResourceRegistry/Frontend/ServiceResourceFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ResourceService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/appid-502/resource.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resources.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resourcesfe.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ResourceControllerTest.cs
Labels: kind/feature-request

#1077 Update deploy-at.yml
  .github/workflows/deploy-at.yml
Labels: kind/bug, bugfix

#1080 Test/fix playwright reports GitHub/1076
  .github/workflows/deploy-at.yml
  .github/workflows/template-playwright.yml
  .yarn/releases/yarn-4.4.1.cjs
  playwright/pages/profile/apidelegeringPage.ts
  playwright/playwright.config.ts
Labels: Test

#1082 generate different report names for different environments to avoid 4…
  .github/workflows/template-playwright.yml
  .yarn/releases/yarn-4.5.0.cjs
  playwright/playwright.config.ts
Labels: kind/bug, bugfix

#1081 Feat: Delegate new service (new GUI)
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/parties.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/51329012.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RegisterClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/RightHolders/51329012.json
  src/components/Avatar/Avatar.module.css
  src/components/Avatar/Avatar.tsx
  src/components/List/List.module.css
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/List/index.ts
  src/components/UserIcon/UserIcon.module.css
  src/components/UserIcon/UserIcon.tsx
  src/components/UserInfoBar/UserInfoBar.tsx
  src/components/index.ts
  src/dataObjects/dtos/resourceDelegation.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModal.module.css
  src/features/amUI/userRightsPage/DelegationModal/DelegationModal.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.module.css
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceSearch.module.css
  src/features/amUI/userRightsPage/DelegationModal/ResourceSearch.tsx
  src/features/amUI/userRightsPage/SingleRightsSection.module.css
  src/features/amUI/userRightsPage/SingleRightsSection.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/features/amUI/users/UserItem/UserItem.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/apiDelegation/apiDelegationApi.ts
  src/rtk/features/lookup/lookupApi.ts
  src/rtk/features/singleRights/singleRightsApi.ts
  src/rtk/features/userInfo/userInfoApi.ts
Labels: kind/feature-request

#1087 Test/rewrite delegation tests
  .github/workflows/template-playwright.yml
  cypress/README.md
  cypress/cypress.config.js
  cypress/package.json
  cypress/pageObjects/Inbox/inbox.js
  cypress/pageObjects/login.js
  cypress/pageObjects/profile3/APIadministration.js
  cypress/pageObjects/profile3/header.js
  cypress/pageObjects/profile3/localRole.js
  cypress/pageObjects/profile3/other-with-rights.js
  cypress/pageObjects/profile3/partyselect.js
  cypress/src/config/at21.json
  cypress/src/config/at22.json
  cypress/src/config/at23.json
  cypress/src/config/at24.json
  cypress/src/config/tt02.json
  cypress/src/e2e/profile/APIdelegering.js
  cypress/src/e2e/profile/idPortenLogin.js
  cypress/src/fixtures/overviewOrgs.ts
  cypress/src/fixtures/pin.json
  cypress/src/support/APIadministration.js
  cypress/src/support/commands.ts
  cypress/src/support/component-index.html
  cypress/src/support/component.ts
  cypress/src/support/e2e.ts
  cypress/src/support/generic-helper.js
  cypress/src/support/idPortenLogin.js
  cypress/src/support/inbox.js
  cypress/src/support/index.js
  cypress/src/support/login.js
  cypress/src/support/other-with-rights-helper.js
  cypress/src/support/party-select.js
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  cypress/support/e2e.ts
  playwright/e2eTests/api-delegering.spec.ts
  playwright/e2eTests/idPortenLogin.spec.ts
  playwright/e2eTests/singleRightsDelegering.spec.ts
  playwright/pages/profile/apidelegeringPage.ts
  playwright/playwright.config.ts
  yarn.lock
Labels: Test

#1089 Run frontend comp tests on all PRs except pure BFF changes
  .github/workflows/continuous-integration-frontend.yml
Labels: Test

#1096 Turn off mock in AT22
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
Labels: kind/chore
