Repository Altinn/altinn-access-management-frontend, pull requests merged in 2024-01, with the labels that each got.

#673 Feat/api delegation/read api id from url
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/rtk/features/apiDelegation/delegableApi/delegableApiSlice.ts
Labels: kind/feature-request

#679 Feat/api delegation/640 change delegation flow
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
  src/features/apiDelegation/offered/ReceiptPage/ReceiptPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/feature-request

#690 Fixed error page
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/routes/Router/Router.tsx
  src/sites/ErrorPage/ErrorPage.module.css
  src/sites/ErrorPage/ErrorPage.tsx
  src/sites/ErrorPage/contents/PageNotFound.tsx
  src/sites/ErrorPage/contents/UnknownError.tsx
  src/sites/ErrorPage/index.ts
  src/sites/NotFoundSite/NotFoundSite.tsx
  src/sites/NotFoundSite/index.ts
Labels: kind/feature-request

#691 Robustifying query subscriptions
  src/rtk/app/store.ts
  src/rtk/features/singleRights/singleRightsApi.ts
  tsconfig.json
  yarn.lock
Labels: kind/bug, bugfix

#680 Feat/general/622 use new search component
  package.json
  src/components/Filter/Filter.tsx
  src/components/Filter/Floatover.module.css
  src/components/Filter/OptionDisplay.module.css
  src/components/Filter/OptionDisplay.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/singleRight/components/SearchSection/SearchSection.module.css
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/resources/utils/debounce.ts
  src/resources/utils/index.ts
  yarn.lock
Labels: kind/feature-request

#710 Update README.md
  README.md
Labels: kind/chore
