Repository Altinn/altinn-access-management-frontend, pull requests merged in 2024-02, with the labels that each got.

#720 Added e2e cypress tests
  .eslintrc.cjs
  .github/workflows/cypress.yml
  .vscode/settings.json
  cypress/README.md
  cypress/cypress.config.js
  cypress/fixtures/example.json
  cypress/package.json
  cypress/pageObjects/Inbox/inbox.js
  cypress/pageObjects/login.js
  cypress/pageObjects/profile3/APIadministration.js
  cypress/pageObjects/profile3/header.js
  cypress/pageObjects/profile3/localRole.js
  cypress/pageObjects/profile3/other-with-rights.js
  cypress/pageObjects/profile3/partyselect.js
  cypress/src/config/at21.json
  cypress/src/config/at22.json
  cypress/src/config/at23.json
  cypress/src/config/at24.json
  cypress/src/config/tt02.json
  cypress/src/e2e/profile/APIdelegering.js
  cypress/src/e2e/profile/idPortenLogin.js
  cypress/src/fixtures/overviewOrgs.ts
  cypress/src/fixtures/pin.json
  cypress/src/support/APIadministration.js
  cypress/src/support/commands.ts
  cypress/src/support/component-index.html
  cypress/src/support/component.ts
  cypress/src/support/e2e.ts
  cypress/src/support/generic-helper.js
  cypress/src/support/idPortenLogin.js
  cypress/src/support/inbox.js
  cypress/src/support/index.js
  cypress/src/support/login.js
  cypress/src/support/other-with-rights-helper.js
  cypress/src/support/party-select.js
  package-lock.json
  package.json
  src/components/Filter/Filter.test.cy.tsx
  src/components/Filter/Floatover.test.cy.tsx
  src/resources/utils/debounce.ts
  yarn.lock
Labels: Cypress

#723 Added query params to redirect in HomeController
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
Labels: kind/bug, bugfix

#724 Handle unauthorized user on delegationCheck
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISingleRightService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SingleRightService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SingleRightClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SingleRightController.cs
  src/features/singleRight/components/ResourceActionBar/ResourceActionBar.tsx
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/errorCodeUtils.ts
  src/rtk/features/singleRights/singleRightsSlice.ts
Labels: kind/feature-request

#735 Read language cookie from altinnPersistentContext
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ProfileHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
Labels: kind/bug, bugfix

#721 Delegate to receiver using url-provided UUID
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IProfileClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IRegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ILookupService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/LookupService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/ProfileClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Profile/userprofile.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Profile/userprofiles.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/parties.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/ProfileClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RegisterClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/LookupControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/LookupController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
  src/features/singleRight/components/RecipientErrorAlert/RecipientErrorAlert.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ReceiptPage/ActionBarSection/ActionBarSection.tsx
  src/features/singleRight/delegate/ReceiptPage/ReceiptPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/hooks/index.ts
  src/resources/hooks/useFetchNameFromUUID.tsx
  src/rtk/app/store.ts
  src/rtk/features/lookup/lookupApi.ts
Labels: kind/feature-request

#743 Updated docker file to create telemetry folder
  Dockerfile
Labels: kind/bug, bugfix

#738 Fix failing unit tests
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ProfileHelper.cs
Labels: kind/bug, bugfix

#749 updated pep package version
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Altinn.AccessManagement.UI.Mocks.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.csproj
Labels: kind/feature-request

#750 Fixed SRR error code not recognized
  src/features/singleRight/components/SearchSection/SearchSection.tsx
Labels: kind/bug, bugfix

#754 Updated PEP package version to 3.0
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Altinn.AccessManagement.UI.Mocks.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.csproj
Labels: kind/feature-request

#719 Feat/api delegation/685 move api search to bff
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IResourceRegistryClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Enums/ResourceType.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ProfileHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/ResourceRegistry/Frontend/ApiSearchParams.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IResourceService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/LookupService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ResourceService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/ResourceRegistryClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resourcesfe.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/ResourceRegistryClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/MaskinportenSchemaControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ResourceControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/MaskinportenSchemaController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/ResourceController.cs
  src/components/Filter/Filter.module.css
  src/components/Filter/Filter.tsx
  src/features/apiDelegation/components/ApiActionBar/ApiActionBar.tsx
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
  src/resources/utils/debounce.ts
  src/rtk/app/store.ts
  src/rtk/features/apiDelegation/apiDelegationApi.ts
  src/rtk/features/apiDelegation/delegableApi/delegableApiSlice.ts
  src/rtk/features/resourceOwner/resourceOwnerApi.ts
  src/rtk/features/singleRights/singleRightsApi.ts
Labels: kind/feature-request

#772 Fix redux store
  src/rtk/app/store.ts
Labels: kind/bug, bugfix

#765 Link back to A2 on finish button
  src/components/PageContainer/PageContainer.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ReceiptPage/ReceiptPage.tsx
  src/resources/hooks/index.ts
  src/resources/hooks/useFetchRecipientInfo.tsx
  src/resources/utils/index.ts
  src/resources/utils/redirectUtils.ts
Labels: kind/feature-request
