Repository Altinn/altinn-access-management-frontend, pull requests merged in 2024-05, with the labels that each got.

#899 New local setup (hybrid solution)
  README.md
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Properties/launchSettings.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
Labels: kind/chore

#891 Display skeleton while initializing single-rights page
  .gitignore
  src/features/singleRight/components/ChooseServiceSkeleton/ChooseServiceSkeleton.module.css
  src/features/singleRight/components/ChooseServiceSkeleton/ChooseServiceSkeleton.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/resources/hooks/useFetchRecipientInfo.tsx
Labels: kind/feature-request

#901 Fix missing release generator workflow
  .github/pr-labels.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/scheduled-release.yml
Labels: kind/chore

#902 Fix rendering service delegations when service has long name
  src/features/singleRight/components/ResourceActionBar/ResourceActionBar.module.css
  src/features/singleRight/components/ResourceActionBar/ResourceActionBar.tsx
Labels: bugfix

#921 Chore/general/789 live regions
  src/components/ErrorPanel/ErrorPanel.tsx
  src/components/StatusMessageForScreenReader/StatusMessageForScreenReader.module.css
  src/components/StatusMessageForScreenReader/StatusMessageForScreenReader.tsx
  src/features/apiDelegation/components/ApiActionBar/ApiActionBar.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ApiSearchResult.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChooseOrgPage.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChosenItems.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/DelegableOrgItems.tsx
  src/features/apiDelegation/offered/ConfirmationPage/ConfirmationPage.tsx
  src/features/apiDelegation/offered/OverviewPage/OverviewPage.tsx
  src/features/apiDelegation/offered/ReceiptPage/ReceiptPage.tsx
  src/features/apiDelegation/received/OverviewPage/OverviewPage.tsx
  src/features/singleRight/components/RecipientErrorAlert/RecipientErrorAlert.tsx
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ReceiptPage/ReceiptActionBarContent/ReceiptActionBarContent.tsx
  src/features/singleRight/delegate/ReceiptPage/ReceiptPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/css/Common.module.css
  src/resources/hooks/useDocumentTitle.tsx
Labels: kind/chore

#923 BFF cleanup
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ILookupClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/APIDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IAPIDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ILookupService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/LookupService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SingleRightService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/UserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/LookupClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SingleRightClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Altinn.AccessManagement.UI.Mocks.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/Delegation/appid-400.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/Delegation/appid-402.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/Delegation/nav_aa_distribution.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/DelegationCheck/appid-136.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/DelegationCheck/appid-400.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/DelegationCheck/default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/RevokeOffered/nav_aa_distribution.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/MaskinportenSchema/RevokeReceived/nav_aa_distribution.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Profile/userprofiles.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ReporteeList/51329012.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SingleRightClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Altinn.AccessManagement.UI.Tests.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/APIDelegationControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/LookupControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ProfileControllerIntegationtest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ResourceControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SingleRightControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/CustomWebApplicationFactory.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/ReporteeList/51329012.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/RequestInputs/MaskinportenSchema/Delegation/Input_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/RequestInputs/MaskinportenSchema/RevokeOffered/Input_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/RequestInputs/MaskinportenSchema/RevokeReceived/Input_Default.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/TestDataUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/APIDelegationController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/LookupController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/ProfileController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/ResourceController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Test.json
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.tsx
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/rtk/app/store.ts
  src/rtk/features/apiDelegation/apiDelegationApi.ts
  src/rtk/features/apiDelegation/delegationRequest/delegationRequestSlice.ts
  src/rtk/features/apiDelegation/overviewOrg/overviewOrgSlice.ts
  src/rtk/features/lookup/lookupApi.ts
  src/rtk/features/resourceApi.ts
  src/rtk/features/singleRights/singleRightsApi.ts
  src/rtk/features/singleRights/singleRightsSlice.ts
  src/rtk/features/userInfo/userInfoSlice.ts
Labels: kind/chore

#926 Changed the term 'servicedesk'
  .github/workflows/scheduled-release.yml
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/bug, bugfix
