Repository Altinn/altinn-access-management-frontend, pull requests merged in 2024-03, with the labels that each got.

#773 Update README.md
  README.md
Labels: kind/chore

#774 Quickfix - synchronous delegation posting
  src/features/singleRight/delegate/ChooseRightsPage/ChooseRightsPage.tsx
Labels: kind/bug, bugfix

#782 Deleted package-lock
  package-lock.json
  yarn.lock
Labels: kind/chore

#799 Feat/#720 cypress GitHub actions
  .github/workflows/cypress.yml
  cypress/cypress.config.js
  cypress/package.json
Labels: kind/feature-request

#802 Support search on service owner
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ResourceService.cs
Labels: kind/feature-request
