Repository Altinn/altinn-access-management-frontend, pull requests merged in 2024-08, with the labels that each got.

#981 Add placeholder for header and left menu
  src/features/amUI/users/UsersFakePageWrapper.module.css
  src/features/amUI/users/UsersFakePageWrapper.tsx
  src/features/amUI/users/UsersPage.tsx
Labels: kind/feature-request

#983 Bugfix: calls to useAppSelector should return the same result
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/request/ChooseServicePage/ChooseServicePage.tsx
Labels: kind/bug, bugfix

#986 Fix typescript type errors
  src/components/CollectionBar/CollectionBar.module.css
  src/components/CollectionBar/CollectionBar.tsx
  src/components/GroupElements/GroupElements.tsx
  src/features/apiDelegation/components/OverviewPageContent/OrgDelegationActionBar/OrgDelegationActionBar.test.cy.tsx
  src/features/apiDelegation/offered/ChooseApiPage/ApiSearchResult.tsx
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/features/singleRight/delegate/ChooseServicePage/ChooseServicePage.tsx
  src/features/singleRight/delegate/ReceiptPage/ActionBarSection/ActionBarSection.tsx
  src/features/singleRight/request/ChooseServicePage/ChooseServicePage.tsx
  src/rtk/features/apiDelegation/overviewOrg/overviewOrgSlice.ts
  src/rtk/features/singleRights/singleRightsSlice.ts
  src/vite-env.d.ts
  tsconfig.json
Labels: kind/chore

#995 Update non major nuget packages (fix)
  .husky/pre-commit
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Altinn.AccessManagement.UI.Core.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ResourceService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Altinn.AccessManagement.UI.Mocks.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.csproj
Labels: kind/bug, kind/chore, bugfix

#987 Søk i brukerliste
  src/components/List/List.tsx
  src/features/amUI/users/UsersList.module.css
  src/features/amUI/users/UsersList.tsx
  src/features/amUI/users/UsersPage.tsx
  src/features/amUI/users/useFilteredRightHolders.ts
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/debounce.ts
Labels: kind/feature-request

#997 Sort right holders list
  src/features/amUI/users/useFilteredRightHolders.ts
Labels: kind/feature-request

#1004 Fix: Confirm button on cancel is too large
  src/features/singleRight/components/NavigationSection/NavigationSection.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/bug, bugfix

#1005 Feat/users/994 one language call to rule them all
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/LanguageHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ProfileHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/HomeControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Helpers/LangugageHelperTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/APIDelegationController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/ResourceController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  src/main.jsx
Labels: kind/feature-request

#1006 Add expand/collapse based on serch-result
  src/features/amUI/users/UserItem/UserItem.tsx
  src/features/amUI/users/useFilteredRightHolders.ts
Labels: kind/feature-request

#1014 Deleted cypress tests which are developed in playwright and fixed playwright failing tests
  .github/workflows/deploy-at.yml
  .github/workflows/playwright.yml
  cypress/package.json
  cypress/src/e2e/profile/APIdelegering.js
  package.json
  playwright/e2eTests/api-delegering.spec.ts
  playwright/e2eTests/singleRightsDelegering.spec.ts
  playwright/jsonReports/jsonReport.json
  playwright/package.json
  playwright/pages/loginPage.ts
  playwright/pages/profile/apidelegeringPage.ts
  playwright/pages/profile/delegationPage.ts
  yarn.lock
Labels: Test

#1016 Made changes in yml file to trigger the pipeline to run tests on every push
  .github/workflows/playwright.yml
Labels: Test

#1019 Made changes in yml file to test pipeline
  .github/workflows/playwright.yml
Labels: Test

#1022 Chore/general/fix eslint import rule
  .eslintrc.cjs
  src/features/amUI/common/FakePageWrapper/FakePageWrapper.tsx
  src/features/amUI/common/PageContainer/PageContainer.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/features/apiDelegation/components/OverviewPageContent/OverviewPageContent.tsx
Labels: kind/chore

#1041 Changed alert text for missing rights error
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/bug, bugfix

#1048 Deleted AT21 config file and added tt02 config file
  .github/workflows/cypress-schedule.yml
  .github/workflows/deploy-at.yml
  playwright/config/.env.at21
  playwright/config/.env.tt02
  playwright/e2eTests/singleRightsDelegering.spec.ts
  playwright/pages/profile/apidelegeringPage.ts
  playwright/pages/profile/delegationPage.ts
  playwright/playwright.config.ts
Labels: Test
