Repository Altinn/altinn-access-management-frontend, pull requests merged in 2024-10, with the labels that each got.

#1102 Deleted unused cypress files and updated cypress version
  cypress/README.md
  cypress/cypress.config.js
  cypress/package.json
  cypress/pageObjects/Inbox/inbox.js
  cypress/pageObjects/login.js
  cypress/pageObjects/profile3/APIadministration.js
  cypress/pageObjects/profile3/header.js
  cypress/pageObjects/profile3/localRole.js
  cypress/pageObjects/profile3/other-with-rights.js
  cypress/pageObjects/profile3/partyselect.js
  cypress/src/config/at21.json
  cypress/src/config/at22.json
  cypress/src/config/at23.json
  cypress/src/config/at24.json
  cypress/src/config/tt02.json
  cypress/src/e2e/profile/APIdelegering.js
  cypress/src/e2e/profile/idPortenLogin.js
  cypress/src/fixtures/pin.json
  cypress/src/support/APIadministration.js
  cypress/src/support/commands.ts
  cypress/src/support/component-index.html
  cypress/src/support/component.ts
  cypress/src/support/e2e.ts
  cypress/src/support/generic-helper.js
  cypress/src/support/idPortenLogin.js
  cypress/src/support/inbox.js
  cypress/src/support/index.js
  cypress/src/support/login.js
  cypress/src/support/other-with-rights-helper.js
  cypress/src/support/party-select.js
  package.json
  yarn.lock
Labels: Test

#1099 Feat/am UI/1091 modal husker siste søk når man går tilbake fra resu
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/app_ttd_a3-app/resource.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/app_ttd_a3-app2/resource.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resourceowners.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resources.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resourcesfe.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/se_3225_1596/resource.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/se_322a_159b/resource.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ResourceControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/ResourceRegistry/resourceOwnersOrgList.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/GetDelegations/delegations.json
  src/features/amUI/userRightsPage/DelegationModal/DelegationModal.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModalContent.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModalContext.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceSearch.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/feature-request

#1100 Fix SRR error message
  src/features/singleRight/components/SearchSection/SearchSection.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/bug, bugfix

#1104 Added error messages for when entire services are undelegable
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ResourceService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/appid-511/resource.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resources.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resourcesfe.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/appid-510.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/GetDelegations/delegations.json
  src/features/amUI/userRightsPage/DelegationModal/ResourceAlert.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.module.css
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/singleRights/singleRightsApi.ts
Labels: kind/feature-request

#1113 Feat/amui/1095 tjenesteeiers logo på tjenester 2
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/CacheConfig.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/ResourceRegistry/Frontend/ServiceResourceFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ResourceService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SingleRightService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/ResourceRegistryClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resourceowners.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/appsettings.test.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  src/features/amUI/common/Avatar/Avatar.module.css
  src/features/amUI/common/Avatar/Avatar.stories.tsx
  src/features/amUI/common/Avatar/Avatar.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceSearch.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightItem.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightsSection.tsx
  src/rtk/features/singleRights/singleRightsApi.ts
Labels: kind/feature-request

#1114 Fix possible cashing error
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/ResourceRegistryClient.cs
Labels: kind/bug, bugfix

#1120 downgrade es-lint
  package.json
  yarn.lock
Labels: kind/bug, bugfix

#1119 Deploy not working
  .github/workflows/template-build-and-test-frontend.yml
Labels: kind/bug, bugfix

#1121 fix typescript errors + rebuild yarn.lock file
  .mock/mockServiceWorker.js
  src/components/ErrorPanel/ErrorPanel.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceAlert.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/ChosenItems.tsx
  src/features/apiDelegation/offered/ChooseOrgPage/DelegableOrgItems.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBar/RightsActionBar.tsx
  src/rtk/features/singleRights/singleRightsSlice.ts
  yarn.lock
Labels: kind/bug, bugfix

#1122 use node:18-alpine in dockerfile
  .yarn/releases/yarn-4.2.2.cjs
  .yarn/releases/yarn-4.5.0.cjs
  Dockerfile
Labels: kind/bug, bugfix

#1127 Handle cases where not all actions can be delegated
  .mock/handlers.js
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/errorCodeUtils.ts
Labels: kind/feature-request

#1130 User can edit actions on delegated service
  .github/workflows/continuous-integration-frontend.yml
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Delegation/RevokeReceivedDelegation.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SingleRight/Frontend/ResourceDelegation.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SingleRight/Frontend/RightChanges.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISingleRightService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SingleRightService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/CreateDelegation/appid-502.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/a3-app2.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/DelegationAccessCheckResponse/appid-502.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/GetDelegations/delegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/RevokeDelegation/appid-502/read.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/RevokeDelegation/appid-502/write.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SingleRight/RevokeDelegation/appid-503/sign.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/HomeControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SingleRightControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SingleRight/GetDelegations/delegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SingleRightController.cs
  src/dataObjects/dtos/resourceDelegation.tsx
  src/features/amUI/common/List/List.module.css
  src/features/amUI/common/PageContainer/PageContainer.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModal.module.css
  src/features/amUI/userRightsPage/DelegationModal/DelegationModalContent.tsx
  src/features/amUI/userRightsPage/DelegationModal/EditModal.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.module.css
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceSearch.module.css
  src/features/amUI/userRightsPage/DelegationModal/ResourceSearch.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/DeleteResourceButton.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightItem.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightsSection.module.css
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightsSection.tsx
  src/features/amUI/users/UserItem/UserItem.tsx
  src/features/amUI/users/UsersList.module.css
  src/features/amUI/users/UsersList.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/hooks/useDelegateRights.tsx
  src/resources/hooks/useEditResource.tsx
  src/resources/hooks/useRevokeResource.tsx
  src/resources/utils/arrayUtils.tsx
  src/resources/utils/index.ts
  src/resources/utils/urnUtils.tsx
  src/rtk/features/lookup/lookupApi.ts
  src/rtk/features/singleRights/singleRightsApi.ts
Labels: kind/feature-request

#1132 Add tabs to right holder page
  .mock/mockServiceWorker.js
  .yarn/releases/yarn-4.5.1.cjs
  src/components/Paginering/AmPaginering.tsx
  src/features/amUI/common/FakePageWrapper/FakePageWrapper.module.css
  src/features/amUI/common/FakePageWrapper/FakePageWrapper.tsx
  src/features/amUI/common/PageContainer/PageContainer.module.css
  src/features/amUI/userRightsPage/DelegationModal/DelegationModal.module.css
  src/features/amUI/userRightsPage/DelegationModal/DelegationModalContent.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/ResourceSearch.module.css
  src/features/amUI/userRightsPage/DelegationModal/ResourceSearch.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightsSection.module.css
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightsSection.tsx
  src/features/amUI/userRightsPage/UserRightsPage.module.css
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/css/Common.module.css
Labels: kind/feature-request

#1134 Force reload when user has changed reportee in another tab
  src/components/ReloadAlert/ReloadAlert.module.css
  src/components/ReloadAlert/ReloadAlert.tsx
  src/features/amUI/common/FakePageWrapper/FakePageWrapper.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/main.jsx
  src/resources/Cookie/CookieMethods.ts
Labels: kind/feature-request
