Repository Altinn/altinn-access-management-frontend, pull requests merged in 2025-04, with the labels that each got.

#1372 Minor changes for agent delegation system user
  .mock/handlers/systemUser.ts
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemRegister/systems.json
  playwright/pages/systemuser/SystemUserPage.ts
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/features/amUI/systemUser/CreateSystemUserPage/RightsIncluded.tsx
  src/features/amUI/systemUser/CreateSystemUserPage/SelectRegisteredSystem.tsx
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/CustomerList.module.css
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/CustomerList.tsx
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPage.module.css
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPageContent.tsx
  src/features/amUI/systemUser/SystemUserAgentRequestPage.tsx
  src/features/amUI/systemUser/SystemUserDetailPage/SystemUserDetailsPage.tsx
  src/features/amUI/systemUser/SystemUsersOverviewPage/SystemUserOverviewPage.test.tsx
  src/features/amUI/systemUser/SystemUsersOverviewPage/SystemUserOverviewPage.tsx
  src/features/amUI/systemUser/components/RightsList/AccessPackageInfo.tsx
  src/features/amUI/systemUser/components/RightsList/RightsList.tsx
  src/features/amUI/systemUser/components/SystemUserHeader/SystemUserHeader.module.css
  src/features/amUI/systemUser/components/SystemUserHeader/SystemUserHeader.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/bug, bugfix

#1383 Chore/amui/1364 delgation check warning icon
  package.json
  src/features/amUI/common/AccessPackageList/AreaItemContent.tsx
  src/features/amUI/common/AccessPackageList/DelegateAccessPackageActionControl.tsx
  src/features/amUI/common/AccessPackageList/RevokeAccessPackageActionControl.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/common/RoleList/DelegateRoleButton.tsx
  src/features/amUI/common/RoleList/RoleList.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRoleSection.tsx
  src/features/amUI/userRightsPage/RoleSection/RoleSection.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/hooks/useAccessPackageDelegationCheck.ts
  yarn.lock
Labels: kind/chore

#1388 Remove extra character caused by copy-paste
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/bug, bugfix

#1390 Use new access package for forretningsfører
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/packages.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemRegister/systems.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/agentSystemUsers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/Search/emptySearch.json
Labels: kind/bug, bugfix

#1389 Send partyUuid as query param instead of looking up partyuuid from partyid in registry
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IRegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RegisterClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserAgentDelegationControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserAgentDelegationController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserController.cs
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/CustomerList.tsx
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPage.tsx
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPageContent.tsx
  src/rtk/features/systemUserApi.ts
Labels: kind/bug, bugfix

#1397 Show snackbar when adding/removing customer from agent systemuser
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/CustomerList.tsx
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPage.module.css
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPageContent.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/feature-request

#1401 Minimize other available packages in area
  src/features/amUI/common/AccessPackageList/AccessPackageList.module.css
  src/features/amUI/common/AccessPackageList/AccessPackageList.tsx
  src/features/amUI/common/AccessPackageList/AreaItemContent.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/PackageSearch.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/ActiveDelegations.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/feature-request

#1404 Add account search functionality & virtualization to PageLayoutWrapper
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
Labels: kind/chore

#1406 Add feature flag for limited preview launch
  .storybook/preview-head.html
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/FeatureFlags.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/RoleControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/RoleController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  src/features/amUI/common/PageLayoutWrapper/SidebarItems.tsx
  src/features/amUI/common/RightsTabs/RightsTabs.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRightsPage.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/features/amUI/users/NewUserModal/NewUserModal.tsx
  src/features/amUI/users/UsersList.tsx
  src/global.d.ts
Labels: kind/chore

#1411 Make scrollbar less noticable
  src/components/Filter/OptionDisplay.module.css
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.module.css
  src/features/amUI/common/DelegationModal/AccessPackages/PackageSearch.module.css
  src/features/apiDelegation/offered/ChooseApiPage/ChooseApiPage.module.css
  src/resources/css/Common.module.css
Labels: kind/feature-request

#1412 Add new org with backend support
  .yarn/releases/yarn-4.8.1.cjs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IRightHolderClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/MockSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/HttpStatusException.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/UserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Altinn.AccessManagement.UI.Integration.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RightHolderClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/UserAccesses/cd35779b-b174-4ecc-bbef-ece13611be7f_3d8b34c3-df0d-4dcc-be12-e788ce414744.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RightHolderClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Test.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  src/features/amUI/users/NewUserModal/NewOrgContent.tsx
  src/features/amUI/users/NewUserModal/NewUserAlert.tsx
  src/rtk/features/userInfoApi.ts
Labels: kind/feature-request

#1419 Fix: double snackbar in customer agent delegation
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/CustomerList.module.css
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPage.tsx
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPageContent.tsx
Labels: kind/bug, bugfix

#1422 Fixed failing playwright test
  playwright/pages/profile/delegationPage.ts
Labels: Test

#1423 Refactor DeleteUserModal to use design system components
  src/features/amUI/userRightsPage/DeleteUserModal.tsx
Labels: kind/chore

#1425 Add language selection functionality
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/chore

#1426 Test using avatars for both to- and from party
  src/features/amUI/common/UserPageHeader/UserPageHeader.module.css
  src/features/amUI/common/UserPageHeader/UserPageHeader.tsx
  src/features/amUI/reporteeRightsPage/ReporteeAccessPackageSection.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRightsPage.tsx
Labels: kind/feature-request
