Repository Altinn/altinn-access-management-frontend, pull requests merged in 2025-05, with the labels that each got.

#1433 Check if email field exists before attempting to fill it out
  playwright/pages/profile/delegationPage.ts
Labels: Test

#1434 Remove forgotten line
  playwright/pages/profile/delegationPage.ts
Labels: Test

#1427 Implement GetRightHolders functionality and update related endpoints
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IRightHolderClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/Connection/Connection.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/Connection/ConnectionMapper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/Connection/PartyInfo.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/Connection/RoleInfo.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/User.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/UserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RightHolderClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/60fb3d5b-99c2-4df0-aa77-f3fca3bc5199.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/cd35779b-b174-4ecc-bbef-ece13611be7f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RightHolderClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/RightHolders/60fb3d5b-99c2-4df0-aa77-f3fca3bc5199.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/RightHolders/cd35779b-b174-4ecc-bbef-ece13611be7f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  src/features/amUI/common/CurrentUserPageHeader/CurrentUserPageHeader.tsx
  src/features/amUI/common/PartyRepresentationContext/PartyRepresentationContext.tsx
  src/features/amUI/common/UserList/UserListItem.tsx
  src/features/amUI/common/UserList/useFilteredUsers.test.ts
  src/features/amUI/common/UserPageHeader/UserPageHeader.tsx
  src/features/amUI/reportees/ReporteesList.tsx
  src/features/amUI/reportees/ReporteesPage.tsx
  src/features/amUI/users/UsersList.tsx
  src/features/amUI/users/UsersPage.tsx
  src/rtk/features/userInfoApi.ts
Labels: kind/chore

#1439 refactor: rename registryRoles to roles in user-related components
  src/features/amUI/common/CurrentUserPageHeader/CurrentUserPageHeader.tsx
  src/features/amUI/common/UserList/UserListItem.tsx
  src/features/amUI/common/UserList/useFilteredUsers.test.ts
  src/features/amUI/users/UsersList.tsx
  src/rtk/features/userInfoApi.ts
Labels: kind/chore

#1446 Secure user info by checking connection
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/ListObjectResult.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/PaginatedResult.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RightHolderClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT23.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT24.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  src/features/amUI/common/AccessPackageList/AccessPackageList.stories.tsx
  src/features/amUI/common/AccessPackageList/AccessPackageList.tsx
  src/features/amUI/common/AccessPackageList/useAccessPackageActions.ts
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/common/DelegationModal/DelegationModal.stories.tsx
  src/features/amUI/common/PartyRepresentationContext/PartyRepresentationContext.tsx
  src/features/amUI/common/RightsTabs/RightsTabs.tsx
  src/features/amUI/common/RoleList/RoleList.stories.tsx
  src/features/amUI/common/UserList/UserList.tsx
  src/features/amUI/common/UserPageHeader/UserPageHeader.tsx
  src/features/amUI/reporteeRightsPage/ReporteeAccessPackageSection.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRightsPage.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRoleSection.tsx
  src/features/amUI/reportees/ReporteePage.module.css
  src/features/amUI/reportees/ReporteesPage.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.tsx
  src/features/amUI/userRightsPage/DeleteUserModal.tsx
  src/features/amUI/userRightsPage/RoleSection/RoleSection.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/DeleteResourceButton.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightItem.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightsSection.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/features/amUI/users/NewUserModal/NewUserModal.tsx
  src/features/amUI/users/UsersList.module.css
  src/features/amUI/users/UsersList.tsx
  src/features/amUI/users/UsersPage.tsx
  src/resources/hooks/useRevokeResource.tsx
  src/rtk/features/lookupApi.ts
  src/rtk/features/userInfoApi.ts
Labels: kind/feature-request

#1448 Fix bug where service owner was not provided to the translated error-message
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.stories.tsx
  src/features/singleRight/delegate/ChooseRightsPage/RightsActionBarContent/RightsActionBarContent.tsx
Labels: kind/bug, bugfix

#1447 Feat/am UI/add authorization to bff
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Altinn.AccessManagement.UI.Core.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/MockSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Constants/AuthzConstants.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Altinn.AccessManagement.UI.Integration.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Configuration/PlatformSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/MockPDP.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Authorization/EndUserResourceAccessHandler.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Authorization/EndUserResourceAccessRequirement.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Authorization/Helpers/AltinnXacmlConstants.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Authorization/Helpers/DecisionHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Test.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  src/features/amUI/common/UserList/ListWrapper.tsx
  src/features/amUI/common/UserList/UserListItem.tsx
  src/features/amUI/users/UsersList.tsx
  src/rtk/features/userInfoApi.ts
Labels: kind/feature-request

#1452 Use new endpoint to get customers for agent system user
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IRegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Constants/Problem.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Enums/CustomerRoleType.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Register/CustomerList.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Register/PartyRecord.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Customer.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/CustomerPartyFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/forretningsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/regnskapsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/revisorCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/forretningsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/regnskapsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/revisorCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RegisterClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserAgentDelegationControllerTest.cs
Labels: kind/chore
