Repository Altinn/altinn-access-management-frontend, pull requests merged in 2025-07, with the labels that each got.

#1498 Add skeletons for types of pages and use it on initial load
  src/features/amUI/common/CurrentUserPageHeader/CurrentUserSkeleton.tsx
  src/features/amUI/common/DeleteUserModal/DeleteUserModal.tsx
  src/features/amUI/common/NotAvailableForUserTypeAlert/NotAvailableForUserTypeAlert.tsx
  src/features/amUI/common/PartyRepresentationContext/PartyRepresentationContext.tsx
  src/features/amUI/common/RightsTabs/TabContentSkeleton.tsx
  src/features/amUI/common/UserList/SkeletonUserList.tsx
  src/features/amUI/common/UserPageHeader/UserPageHeader.tsx
  src/features/amUI/common/UserPageHeader/UserPageHeaderSkeleton.tsx
  src/features/amUI/common/alertIfNotAvailableForUserType/AlertIfNotAvailableForUserType.tsx
  src/features/amUI/reporteeRightsPage/ReporteeAccessPackageSection.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRightsPage.tsx
  src/features/amUI/reporteeRightsPage/RoleInfoModal.tsx
  src/features/amUI/reportees/ReporteesList.tsx
  src/features/amUI/reportees/ReporteesPage.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/features/amUI/users/UsersList.tsx
  src/features/amUI/users/UsersPage.tsx
Labels: kind/bug, bugfix

#1507 Use new A3-app for e2e testing
  playwright/config/.env.at24
  playwright/config/.env.tt02
  playwright/e2eTests/singleRightsDelegering.spec.ts
Labels: Test

#1460 Add endpoints to get, aprove and reject consent request
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Altinn.AccessManagement.UI.Core.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IConsentClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/MockSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Constants/ConsentProblem.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ConsentProblemMapper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/MarkdownConverter.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/ApproveConsentContext.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/ConsentRequestDetails.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/ConsentRequestEventDto.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/ConsentResourceAttribute.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/ConsentRight.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/ConsentTemplate.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/ConsentTemplateTexts.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/ConsentTemplateTypeText.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/EnrichedConsentTemplate.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/Frontend/ConsentRequestFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/Frontend/ConsentRightFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/ResourceRegistry/ConsentMetadata.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/ResourceRegistry/ServiceResource.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ConsentService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IConsentService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/ConsentClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Configuration/PlatformSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Consent/consentRequest_org.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Consent/consentRequest_person.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Consent/consentTemplates.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/parties.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/consent-test-resource-poa/resource.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/consent-test-resource/resource.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/regnskapsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/ConsentClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/EncryptionServiceMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RegisterClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/ConsentControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/LogoutRedirectControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserAgentDelegationControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/Consent/consentRequest_org.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/Consent/consentRequest_person.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/regnskapsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/ConsentController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/LogoutRedirectController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Test.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
Labels: kind/feature-request

#1508 Use new registry endpoint for fetching party data
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Altinn.AccessManagement.UI.Core.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IRegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/Frontend/PartyFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Register/PartyR.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Register/PartyType.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ILookupService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/LookupService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/parties.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/partiesOld.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RegisterClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/LookupControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/LookupController.cs
  src/features/amUI/common/AccessPackageList/DelegateAccessPackageActionControl.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/common/PartyRepresentationContext/PartyRepresentationContext.tsx
  src/features/amUI/common/UserList/ListWrapper.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.tsx
  src/resources/hooks/useFetchRecipientInfo.tsx
  src/rtk/features/lookupApi.ts
Labels: kind/bug, bugfix

#1513 Visual fixes before TT02
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessPackageClient.cs
  src/features/amUI/common/AccessPackageList/AccessPackageExpandedContext.tsx
  src/features/amUI/common/AccessPackageList/AccessPackageList.module.css
  src/features/amUI/common/AccessPackageList/AccessPackageList.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/PackageSearch.module.css
  src/features/amUI/common/DelegationModal/AccessPackages/PackageSearch.tsx
  src/features/amUI/common/DelegationModal/DelegationModalContext.tsx
  src/features/amUI/common/DeleteUserModal/DeleteUserModal.tsx
  src/features/amUI/common/UserList/UserListItem.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.tsx
  src/features/amUI/users/NewUserModal/NewOrgContent.tsx
  src/features/amUI/users/UsersList.module.css
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/accessPackageApi.ts
Labels: kind/bug, bugfix

#1515 Update feature flags to display limited preview launch in TT02
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.TT02.json
Labels: kind/feature-request

#1509 client delegation tests should handle logout - but it doesnt work. so…
  playwright/e2eTests/systemuser/clientDelegation.spec.ts
  playwright/pages/loginPage.ts
Labels: Test

#1517 Add timezones to Docker image
  Dockerfile
Labels: kind/bug, bugfix

#1522 Fix: set escapeValue: false for i18n interpolation
  src/main.jsx
Labels: kind/bug, bugfix

#1526 Feat/amUI/906-vise-tjenestebilder-i-pakke-modalen
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAltinnCdnClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/MockSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/OrgData.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/AltinnCdnService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IAltinnCdnService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AltinnCdnClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AltinnCdn/altinn-orgs.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AltinnCdnClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/AltinnCdnControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AltinnCdn/orgData.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/AltinnCdnController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Test.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/useMinimizableResourceList.ts
  src/rtk/app/store.ts
  src/rtk/features/accessPackageApi.ts
  src/rtk/features/altinnCdnApi.ts
Labels: kind/feature-request

#1527 Test/fix systemuser login
  playwright/e2eTests/idPortenLogin.spec.ts
  playwright/e2eTests/systemuser/approveSystemUserChangeRequest.spec.ts
  playwright/e2eTests/systemuser/approveSystemUserRequest.spec.ts
  playwright/e2eTests/systemuser/clientDelegation.spec.ts
  playwright/e2eTests/systemuser/deleteSystemUser.spec.ts
  playwright/e2eTests/systemuser/selectSystemVendor.spec.ts
  playwright/fixture/pomFixture.ts
  playwright/pages/LoginPage.ts
  playwright/pages/loginPage.ts
  playwright/playwright.config.ts
Labels: Test

#1531 Add Power of Attorney overview page and update sidebar items
  src/features/amUI/common/PageLayoutWrapper/SidebarItems.tsx
  src/features/amUI/poaOverview/PoaOverviewPage.tsx
  src/features/amUI/poaOverview/index.ts
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/featureFlagUtils.tsx
  src/routes/Router/Router.tsx
  src/routes/paths/amUIPath.tsx
Labels: kind/chore

#1532 Test/fix capital letter filepath
  .github/workflows/template-playwright.yml
  playwright/pages/LoginPage.ts
  playwright/util/loadFacilitators.ts
Labels: Test

#1535 Consent request fixes after QA with design
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/Frontend/ConsentRequestFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ConsentService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Consent/consentRequest_org.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Consent/consentRequest_org_without_message.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Consent/consentRequest_person.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/Consent/consentRequest_person.json
  src/features/amUI/consent/ConsentRequestPage/ConsentRequestPage.module.css
  src/features/amUI/consent/ConsentRequestPage/ConsentRequestPage.tsx
  src/features/amUI/consent/types.ts
  src/localizations/no_nb.json
Labels: kind/bug, bugfix
