Repository Altinn/altinn-access-management-frontend, pull requests merged in 2025-02, with the labels that each got.

#1256 Chore/amui/vitest test runner
  .github/workflows/template-build-and-test-frontend.yml
  .gitignore
  .mock/mockServiceWorker.js
  package.json
  src/resources/utils/arrayUtils.test.ts
  src/resources/utils/arrayUtils.test.tsx
  src/resources/utils/arrayUtils.tsx
  src/resources/utils/roleUtils.test.ts
  src/resources/utils/roleUtils.ts
  vitest.config.ts
  yarn.lock
Labels: kind/chore

#1258 sonar.coverage.exclusions parameter
  .github/workflows/template-build-and-test-backend.yml
Labels: kind/feature-request

#1267 Feature/end to end 1190
  playwright/e2eTests/singleRightsDelegering.spec.ts
  playwright/pages/profile/delegationPage.ts
Labels: Test

#1269 Removed temporary PartyUuid cookie fix
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/HomeControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
Labels: kind/feature-request

#1265 Feat/amui/277 reportee list page
  .vscode/settings.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/User.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/UserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ReporteeList/GetPartyFromReporteeList/51329012.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ReporteeList/GetPartyFromReporteeList/51473841.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ReporteeList/reporteeList.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientV0Mock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/ReporteeList/51329012.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/ReporteeList/GetPartyFromReporteeList/51329012.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/ReporteeList/cd35779b-b174-4ecc-bbef-ece13611be7f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  package.json
  src/features/amUI/common/CurrentUserPageHeader/CurrentUserPageHeader.module.css
  src/features/amUI/common/CurrentUserPageHeader/CurrentUserPageHeader.tsx
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/features/amUI/common/UserList/ListWrapper.tsx
  src/features/amUI/common/UserList/SkeletonUserList.tsx
  src/features/amUI/common/UserList/UserList.module.css
  src/features/amUI/common/UserList/UserList.tsx
  src/features/amUI/common/UserList/UserListItem.tsx
  src/features/amUI/common/UserList/useFilteredUsers.test.ts
  src/features/amUI/common/UserList/useFilteredUsers.ts
  src/features/amUI/reportees/ReporteePage.module.css
  src/features/amUI/reportees/ReporteesPage.tsx
  src/features/amUI/users/UserItem/UserItem.module.css
  src/features/amUI/users/UserItem/UserItem.tsx
  src/features/amUI/users/UserItem/index.ts
  src/features/amUI/users/UsersList.module.css
  src/features/amUI/users/UsersList.tsx
  src/features/amUI/users/useFilteredRightHolders.ts
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/routes/Router/Router.tsx
  src/routes/paths/amUIPath.tsx
  src/rtk/features/userInfoApi.ts
  vite.config.ts
  vitest.config.ts
  yarn.lock
Labels: kind/feature-request

#1273 Update altinn component version and integrate new features
  package.json
  src/features/amUI/common/ButtonWithConfirmPopup/ButtonWithConfirmPopup.module.css
  src/features/amUI/common/ButtonWithConfirmPopup/ButtonWithConfirmPopup.tsx
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/features/amUI/common/Snackbar/Snackbar.tsx
  src/features/amUI/common/Snackbar/SnackbarProvider.tsx
  src/features/amUI/common/UserList/UserListItem.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DelegatedAreaListItem.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DelegatedPackagesList.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessAreaListItem.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/SingleRights/ResourceInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/SingleRights/ResourceSearch.tsx
  src/features/amUI/userRightsPage/RoleSection/RoleListItem.tsx
  src/features/amUI/userRightsPage/RoleSection/RoleSection.tsx
  yarn.lock
Labels: kind/feature-request

#1272 add reportee rights page and related components
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessManagement/UserAccesses.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/UserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/05bbad70-90db-4900-8f29-0a09cf6db1af.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/parties.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ReporteeList/reporteeList.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/51329012.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/UserAccesses/05bbad70-90db-4900-8f29-0a09cf6db1af_cd35779b-b174-4ecc-bbef-ece13611be7f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/UserAccesses/cd35779b-b174-4ecc-bbef-ece13611be7f_05bbad70-90db-4900-8f29-0a09cf6db1af.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/UserAccesses/cd35779b-b174-4ecc-bbef-ece13611be7f_167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/UserAccesses/cd35779b-b174-4ecc-bbef-ece13611be7f_26ca8b02-c455-4dc0-96be-f92864837ff9.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/UserAccesses/cd35779b-b174-4ecc-bbef-ece13611be7f_5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/UserAccesses/cd35779b-b174-4ecc-bbef-ece13611be7f_ebd192ea-753b-448e-9226-95e8c439bd9f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/ReporteeList/cd35779b-b174-4ecc-bbef-ece13611be7f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/RightHolders/51329012.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  src/features/amUI/ReporteeRightsPage/ReporteeRightsPage.tsx
  src/features/amUI/common/RightsTabs/RightsTabs.tsx
  src/features/amUI/common/UserPageHeader/UserPageHeader.module.css
  src/features/amUI/common/UserPageHeader/UserPageHeader.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/routes/Router/Router.tsx
  src/routes/paths/amUIPath.tsx
  src/rtk/features/userInfoApi.ts
Labels: kind/feature-request

#1274 Use correct access management client
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ResourceHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserService.cs
  src/features/amUI/systemUser/SystemUsersOverviewPage/SystemUserOverviewPage.tsx
Labels: kind/chore

#1279 Fix mapping of systemuser error messages
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Constants/Problem.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ProblemMapper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/SystemUserCreateResponseFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserChangeRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Helpers/ProblemMapperTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserController.cs
  src/features/amUI/systemUser/CreateSystemUserPage/RightsIncluded.tsx
  src/features/amUI/systemUser/components/DelegationCheckError/DelegationCheckError.tsx
  src/rtk/features/systemUserApi.ts
Labels: kind/bug, bugfix

#1280 Fix access package list items from backend
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ResourceHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ResourceUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/RegisteredSystem.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/RegisteredSystemAccessPackage.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/SystemUserChangeRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/SystemUserRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemRegister/systems.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/systemUserRequest.json
Labels: kind/bug, bugfix

#1281 Feat/amui/281 reportee rights page packages
  .mock/handlers/accessPackage.ts
  .mock/handlers/data/packages.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/05bbad70-90db-4900-8f29-0a09cf6db1af_cd35779b-b174-4ecc-bbef-ece13611be7f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/cd35779b-b174-4ecc-bbef-ece13611be7f_05bbad70-90db-4900-8f29-0a09cf6db1af.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/cd35779b-b174-4ecc-bbef-ece13611be7f_167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/cd35779b-b174-4ecc-bbef-ece13611be7f_26ca8b02-c455-4dc0-96be-f92864837ff9.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/cd35779b-b174-4ecc-bbef-ece13611be7f_5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/cd35779b-b174-4ecc-bbef-ece13611be7f_ebd192ea-753b-448e-9226-95e8c439bd9f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/UserAccesses/05bbad70-90db-4900-8f29-0a09cf6db1af_cd35779b-b174-4ecc-bbef-ece13611be7f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Roles/GetRolesForUser/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/Role/GetRolesForUser/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  src/features/amUI/common/AccessPackageList/AccessPackageList.module.css
  src/features/amUI/common/AccessPackageList/AccessPackageList.stories.tsx
  src/features/amUI/common/AccessPackageList/AccessPackageList.tsx
  src/features/amUI/common/AccessPackageList/AreaItem.tsx
  src/features/amUI/common/AccessPackageList/PackageItem.tsx
  src/features/amUI/common/AccessPackageList/SkeletonAccessPackageList.tsx
  src/features/amUI/common/AccessPackageList/useAccessPackageActions.ts
  src/features/amUI/common/AccessPackageList/useAreaPackageList.ts
  src/features/amUI/common/UserList/ListWrapper.tsx
  src/features/amUI/common/UserList/UserList.module.css
  src/features/amUI/reporteeRightsPage/ReporteeAccessPackageSection.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRightsPage.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.module.css
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/ActiveDelegations.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DelegatedAreaListItem.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DelegatedPackagesList.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DeletePackageButton.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessAreaListItem.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageSection.module.css
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/PackageSearch.module.css
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/PackageSearch.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/routes/Router/Router.tsx
  src/rtk/features/accessPackageApi.ts
Labels: kind/feature-request

#1287 Linking in header and footer
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/pathUtils.tsx
Labels: kind/feature-request
