Repository Altinn/altinn-access-management-frontend, pull requests merged in 2025-09, with the labels that each got.

#1557 Feat/am UI/804 package page
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessPackageClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessPackage/Frontend/AccessPackageFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/Entity.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/Connection/Entity.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/AccessPackageService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IAccessPackageService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessPackageClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/cd35779b-b174-4ecc-bbef-ece13611be7f_.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessPackageClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/AccessPackageControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/GetSinglePackagePermissions/cd35779b-b174-4ecc-bbef-ece13611be7f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/AccessPackageController.cs
  package.json
  src/dataObjects/dtos/Common.tsx
  src/features/amUI/common/AccessPackageList/AccessPackageList.tsx
  src/features/amUI/common/AccessPackageList/AreaItemContent.tsx
  src/features/amUI/common/AccessPackageList/PackageItem.tsx
  src/features/amUI/common/AccessPackageList/SkeletonAccessPackageList.tsx
  src/features/amUI/common/AccessPackageList/UndelegatedPackageWarning.module.css
  src/features/amUI/common/DelegationModal/AccessPackages/useResourceList.tsx
  src/features/amUI/common/UserList/SkeletonUserList.tsx
  src/features/amUI/common/UserList/UserItem.tsx
  src/features/amUI/common/UserList/UserList.tsx
  src/features/amUI/packagePoaDetailsPage/PackagePoaDetails.tsx
  src/features/amUI/packagePoaDetailsPage/PackagePoaDetailsHeader.module.css
  src/features/amUI/packagePoaDetailsPage/PackagePoaDetailsHeader.tsx
  src/features/amUI/packagePoaDetailsPage/PackagePoaDetailsHeaderSkeleton.tsx
  src/features/amUI/packagePoaDetailsPage/PackagePoaDetailsPage.module.css
  src/features/amUI/packagePoaDetailsPage/PackagePoaDetailsPage.tsx
  src/features/amUI/poaOverview/AccessPackagePermissions.tsx
  src/features/amUI/poaOverview/PoaOverviewPage.module.css
  src/features/amUI/poaOverview/PoaOverviewPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/routes/Router/Router.tsx
  src/routes/paths/amUIPath.tsx
  src/rtk/features/accessPackageApi.ts
  yarn.lock
Labels: kind/feature-request

#1573 Disable limited preview launch feature in app settings
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
Labels: kind/feature-request

#1564 GET rights and access packages for standard systemusers from new endpoint
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/FeatureFlags.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Constants/Problem.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/StandardSystemUserDelegations.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.TT02.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
Labels: kind/feature-request

#1574 Enable access packages for standard system user in AT22
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
Labels: kind/chore

#1571 Feat/am UI/472 irl delegation check
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessPackageClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessPackage/DelegationCheck.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/Frontend/AccessPackageDelegationCheckResponse.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/Frontend/DelegationCheckRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/Frontend/DelegationCheckResponse.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/AccessPackageService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IAccessPackageService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IRoleService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/RoleService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessManagementClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessPackageClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/04c5a001-5249-4765-ae8e-58617c404223.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/0bb5963e-df17-4f35-b913-3ce10a34b866.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/452bd15d-2cd2-4279-9470-cd97ba8ef1c7.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/5eb07bdc-5c3c-4c85-add3-5405b214b8a3.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/78c21107-7d2d-4e85-af82-47ea0e47ceca.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/906aec0d-ad1f-496b-a0bb-40f81b3303cb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/9d2ec6e9-5148-4f47-9ae4-4536f6c9c1cb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/DelegationCheck.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/a03af7d5-74b9-4f18-aead-5d47edc36be5.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/ab656cf2-1e65-4b5a-a1e3-cd5bd4cb804c.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/cfe074fa-0a66-4a4b-974a-5d1db8eb94e6.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Roles/DelegationCheck/15d0015f-e21d-405a-89c5-a21476ba3df0.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Roles/DelegationCheck/37d2ba7f-187f-45f5-9a96-2f23cf328dab.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Roles/DelegationCheck/3abe9842-06a5-483f-b76d-a65dec152b2d.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Roles/DelegationCheck/4691c710-e0ad-4152-9783-9d1e787f02d3.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Roles/DelegationCheck/c46a568e-59ba-4835-8c0f-9a3e7d3d308c.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessPackageClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/AccessPackageControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/RoleControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/DelegationCheck/DelegationCheck.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/PackageDelegationCheck_returns_list.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/AccessPackageController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/RoleController.cs
  src/features/amUI/common/AccessPackageList/AccessPackageList.tsx
  src/features/amUI/common/AccessPackageList/AreaItemContent.tsx
  src/features/amUI/common/AccessPackageList/DelegateAccessPackageActionControl.tsx
  src/features/amUI/common/DelegationCheck/AccessPackageDelegationCheckContext.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/common/DelegationModal/StatusSection.tsx
  src/features/amUI/common/PartyRepresentationContext/PartyRepresentationContext.tsx
  src/resources/hooks/useAccessPackageDelegationCheck.ts
  src/rtk/features/accessPackageApi.ts
Labels: kind/feature-request

#1581 Action aria labels inform user which package they are giving access to
  src/features/amUI/common/AccessPackageList/AreaItemContent.tsx
  src/features/amUI/common/AccessPackageList/DelegateAccessPackageActionControl.tsx
  src/features/amUI/common/AccessPackageList/RevokeAccessPackageActionControl.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: bugfix

#1595 Added test case for delegating access pacakage from Org-1(Avgiver) to Org-2(Rettighetshaver)
  .yarn/releases/yarn-4.9.4.cjs
  playwright/api-requests/Token.tsx
  playwright/api-requests/delegation-tilgangspakke/delegationApiRequest.ts
  playwright/config/.env.at24
  playwright/config/.env.tt02
  playwright/e2eTests/accesspkgdelegation/accesspkgDirectdelegatation.spec.ts
  playwright/fixture/pomFixture.ts
  playwright/pages/profile/accessPkgDelegationPage.ts
  playwright/pages/profile/brukerflateDelegtionPage.ts
  playwright/playwright.config.ts
  playwright/util/delegationApiUtil.ts
  playwright/uuTests/accessibilityHelpers/delegeringHelper.ts
  playwright/uuTests/accessibilityTests/enkelttjenesteDelegering.spec.ts
  tsconfig.json
Labels: Test

#1621 Added API endpoints for delegating access pacakge to run tests isolated
  playwright/api-requests/Token.tsx
  playwright/api-requests/delegation-tilgangspakke/delegationApiRequest.ts
  playwright/config/.env.at24
  playwright/config/.env.tt02
  playwright/e2eTests/accesspkgdelegation/accesspkgDirectdelegatation.spec.ts
  playwright/util/delegationApiUtil.ts
Labels: Test

#1631 Test/playwright reporting improvement
  .github/workflows/deploy-at.yml
  .github/workflows/template-playwright.yml
Labels: Test

#1637 chore: move enrichment of party names in consent template from backend to frontend
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/EnrichedConsentTemplate.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/Frontend/ConsentFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Consent/Frontend/ConsentRequestFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/ConsentService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/Consent/consentRequest_org.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/Consent/consentRequest_org_without_message.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/Consent/consentRequest_person.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/Consent/consent_org.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  src/features/amUI/consent/ConsentHistoryPage/ConsentTimeline.tsx
  src/features/amUI/consent/ConsentRequestPage/ConsentRequestPage.tsx
  src/features/amUI/consent/components/ConsentDetails/ConsentDetails.tsx
  src/features/amUI/consent/types.ts
  src/features/amUI/consent/utils.ts
Labels: kind/chore
