Repository Altinn/altinn-access-management-frontend, pull requests merged in 2025-03, with the labels that each got.

#1288 Add test framework for unit testing React components
  .mock/browser.ts
  .mock/handlers.ts
  .mock/handlers/systemUser.ts
  .mock/handlers/user.ts
  .mock/node.ts
  package.json
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/features/amUI/common/UserList/useFilteredUsers.test.ts
  src/features/amUI/systemUser/SystemUsersOverviewPage/SystemUserOverviewPage.test.tsx
  src/features/amUI/systemUser/components/RightsList/RightsList.test.tsx
  src/features/amUI/systemUser/components/RightsList/RightsList.tsx
  src/rtk/features/userInfoApi.ts
  tests/consts.ts
  tests/setupTests.ts
  tsconfig.json
  vitest.config.ts
  yarn.lock
Labels: kind/chore

#1298 Error handling in modal on package delegation or revoking
  .mock/mockServiceWorker.js
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientMock.cs
  src/features/amUI/common/AccessPackageList/AccessPackageList.tsx
  src/features/amUI/common/AccessPackageList/useAccessPackageActions.ts
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/features/amUI/common/TechnicalErrorParagraphs/TechnicalErrorParagraphs.tsx
  src/features/amUI/common/UserRoles/UserRoles.tsx
  src/features/amUI/reporteeRightsPage/ReporteeAccessPackageSection.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageInfoModal.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/ActiveDelegations.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DeletePackageButton.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/PackageSearch.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModalContent.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModalContext.tsx
  src/features/amUI/userRightsPage/DelegationModal/EditModal.tsx
  src/features/amUI/userRightsPage/RoleSection/RoleInfoModal.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightItem.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/hooks/useActionError.tsx
  src/resources/hooks/useDelegateAccessPackage.tsx
  src/resources/hooks/useRevokeAccessPackage.tsx
Labels: kind/feature-request

#1302 Add API for client systemuser request
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserClientRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/MockSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/SystemUserClientRequestFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/SystemUserClientRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserClientRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserClientRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserClientRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/systemUserClientRequest.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserClientRequestClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserClientRequestControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/systemUserClientRequest.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserClientRequestController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Test.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
Labels: kind/feature-request

#1304 Fix "global"-meny og aktørvalg
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessManagementClientV0.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/UserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessManagementClientV0.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ReporteeList/1234.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessManagementClientV0Mock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/ReporteeList/GetReporteeListForUser/reporteeList.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/features/amUI/common/PageLayoutWrapper/SidebarItems.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/pathUtils.tsx
  src/rtk/features/userInfoApi.ts
Labels: kind/feature-request

#1307 Deploy to YT on release
  .github/workflows/deploy-release.yml
Labels: kind/chore

#1290 Tilgange hos andre | Administratortilganger
  src/features/amUI/common/AccessPackageList/AccessPackageList.tsx
  src/features/amUI/common/AccessPackageList/useAccessPackageActions.ts
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.module.css
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/PackageSearch.module.css
  src/features/amUI/common/DelegationModal/AccessPackages/PackageSearch.tsx
  src/features/amUI/common/DelegationModal/DelegationModal.module.css
  src/features/amUI/common/DelegationModal/DelegationModal.stories.tsx
  src/features/amUI/common/DelegationModal/DelegationModal.tsx
  src/features/amUI/common/DelegationModal/DelegationModalContent.tsx
  src/features/amUI/common/DelegationModal/DelegationModalContext.tsx
  src/features/amUI/common/DelegationModal/EditModal.tsx
  src/features/amUI/common/DelegationModal/Role/RoleInfo.module.css
  src/features/amUI/common/DelegationModal/Role/RoleInfo.tsx
  src/features/amUI/common/DelegationModal/SingleRights/ResourceAlert.tsx
  src/features/amUI/common/DelegationModal/SingleRights/ResourceInfo.module.css
  src/features/amUI/common/DelegationModal/SingleRights/ResourceInfo.tsx
  src/features/amUI/common/DelegationModal/SingleRights/ResourceSearch.module.css
  src/features/amUI/common/DelegationModal/SingleRights/ResourceSearch.tsx
  src/features/amUI/common/List/List.tsx
  src/features/amUI/common/List/ListItem.tsx
  src/features/amUI/common/RoleList/DelegateRoleButton.tsx
  src/features/amUI/common/RoleList/RequestRoleButton.tsx
  src/features/amUI/common/RoleList/RevokeRoleButton.tsx
  src/features/amUI/common/RoleList/RoleInfoModal.tsx
  src/features/amUI/common/RoleList/RoleList.tsx
  src/features/amUI/common/RoleList/RoleListItem.tsx
  src/features/amUI/common/RoleList/SkeletonRoleList.tsx
  src/features/amUI/common/RoleList/roleSection.module.css
  src/features/amUI/common/UserRoles/UserRoles.tsx
  src/features/amUI/reporteeRightsPage/ReporteeAccessPackageSection.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRightsPage.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRoleSection.tsx
  src/features/amUI/reporteeRightsPage/RoleInfoModal.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageInfoModal.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/ActiveDelegations.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DeletePackageButton.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/PackageSearch.tsx
  src/features/amUI/userRightsPage/RoleSection/RoleListItem.tsx
  src/features/amUI/userRightsPage/RoleSection/RoleSection.tsx
  src/features/amUI/userRightsPage/RoleSection/roleSection.module.css
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightItem.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightsSection.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/hooks/useDelegateRights.tsx
  src/resources/hooks/useEditResource.tsx
  src/rtk/features/roleApi.ts
Labels: kind/feature-request

#1313 Hide single rights feature behind feature toggle
  .storybook/preview-head.html
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/FeatureFlags.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  src/features/amUI/common/PageLayoutWrapper/SidebarItems.tsx
  src/features/amUI/common/RightsTabs/RightsTabs.tsx
  src/features/amUI/reporteeRightsPage/ReporteeAccessPackageSection.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageInfoModal.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/ActiveDelegations.tsx
  src/global.d.ts
  src/resources/utils/featureFlagUtils.tsx
Labels: kind/feature-request

#1319 fix(SearchSection): remove controlled input and use debounced search
  src/features/singleRight/components/SearchSection/SearchSection.tsx
Labels: kind/bug, bugfix

#1318 Remove systemuser overrides for old version of designsystemet
  src/features/amUI/systemUser/components/RightsList/RightsList.tsx
  src/resources/css/systemuser.css
Labels: kind/bug, bugfix

#1306 Add UI to approve/reject client delegation system user request
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserClientRequestController.cs
  src/features/amUI/systemUser/SystemUserClientRequestPage.tsx
  src/features/amUI/systemUser/types.ts
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/routes/Router/Router.tsx
  src/routes/paths/systemUserPath.ts
  src/rtk/features/systemUserApi.ts
Labels: kind/feature-request

#1322 Fix: rename client to agent for request
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserAgentRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/SystemUserAgentRequestFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/SystemUserAgentRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserAgentRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserClientRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserAgentRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/systemUserAgentRequest.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserAgentRequestClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserClientRequestClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserAgentRequestControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/systemUserAgentRequest.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserAgentRequestController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  src/features/amUI/systemUser/SystemUserAgentRequestPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/routes/Router/Router.tsx
  src/routes/paths/systemUserPath.ts
  src/rtk/features/systemUserApi.ts
Labels: kind/bug, bugfix

#1291 Fjern elementer som ikke er i bruk i når systembruker lanseres i nytt UI
  src/features/amUI/systemUser/SystemUsersOverviewPage/SystemUserOverviewPage.tsx
Labels: kind/bug, bugfix

#1324 Fix urls to agent request endpoints
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserAgentRequestClient.cs
Labels: kind/bug, bugfix

#1325 Fixed app which was failing in tt02 to instantiate
  playwright/config/.env.at24
  playwright/config/.env.tt02
  playwright/e2eTests/singleRightsDelegering.spec.ts
Labels: Test

#1329 fix wrong text keys in change request page
  src/features/amUI/systemUser/SystemUserChangeRequestPage.tsx
Labels: kind/bug, bugfix

#1331 Add list margin to systemuser rightsList component
  src/features/amUI/systemUser/components/RightsList/RightsList.module.css
  src/features/amUI/systemUser/components/RightsList/RightsList.tsx
Labels: kind/bug, bugfix

#1332 Refactor: move system user delete popover out as a new component
  src/features/amUI/systemUser/SystemUserDetailPage/SystemUserDetailsPage.module.css
  src/features/amUI/systemUser/SystemUserDetailPage/SystemUserDetailsPage.tsx
  src/features/amUI/systemUser/components/DeleteSystemUserPopover/DeleteSystemUserPopover.module.css
  src/features/amUI/systemUser/components/DeleteSystemUserPopover/DeleteSystemuserPopover.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/chore

#1336 Show more specific error messages for systemuser request
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserAgentRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserChangeRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserRequestClient.cs
  src/features/amUI/systemUser/SystemUserChangeRequestPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/bug, bugfix

#1337 update font stylesheet links to use version 4.1
  .storybook/preview-head.html
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Views/Home/Index.cshtml
  index.html
Labels: kind/chore

#1338 Test/systemuser new url
  playwright/README.md
  playwright/config/.env.at22
  playwright/e2eTests/systemuser/approveSystemUserChangeRequest.spec.ts
  playwright/e2eTests/systemuser/approveSystemUserRequest.spec.ts
  playwright/util/Util.tsx
Labels: Test

#1339 Add endpoints to get agent system users
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemRegister/systems.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/agentSystemUsers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/agentSystemUser.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/agentSystemUsers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/systemUser.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/systemUsers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserController.cs
Labels: kind/feature-request

#1340 Use new url to GET agent systemuser request
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/SystemUserAgentRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserAgentRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserAgentRequestController.cs
Labels: kind/bug, bugfix

#1330 Fix loading skeleton for current user in header component
  src/features/amUI/common/CurrentUserPageHeader/CurrentUserPageHeader.tsx
  src/features/amUI/common/CurrentUserPageHeader/CurrentUserSkeleton.tsx
Labels: kind/feature-request

#1326 Feat/amui/402 delegation check on access package
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IAccessPackageClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/Frontend/AccessPackageDelegationCheckResponse.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/Frontend/DelegationCheckRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/AccessPackageService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IAccessPackageService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessPackageClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/04c5a001-5249-4765-ae8e-58617c404223.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/0bb5963e-df17-4f35-b913-3ce10a34b866.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/452bd15d-2cd2-4279-9470-cd97ba8ef1c7.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/5eb07bdc-5c3c-4c85-add3-5405b214b8a3.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/78c21107-7d2d-4e85-af82-47ea0e47ceca.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/906aec0d-ad1f-496b-a0bb-40f81b3303cb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/9d2ec6e9-5148-4f47-9ae4-4536f6c9c1cb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/a03af7d5-74b9-4f18-aead-5d47edc36be5.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/ab656cf2-1e65-4b5a-a1e3-cd5bd4cb804c.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/cfe074fa-0a66-4a4b-974a-5d1db8eb94e6.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/cd35779b-b174-4ecc-bbef-ece13611be7f_5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/UserAccesses/cd35779b-b174-4ecc-bbef-ece13611be7f_5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessPackageClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/AccessPackageControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/GetDelegations/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/PackageDelegationCheck_returns_list.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/RightHolders/RightHolderAccess/5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/AccessPackageController.cs
  src/features/amUI/common/AccessPackageList/AccessPackageList.tsx
  src/features/amUI/common/AccessPackageList/AreaItemContent.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.module.css
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/common/TechnicalErrorParagraphs/TechnicalErrorParagraphs.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/hooks/useAccessPackageDelegationCheck.ts
  src/rtk/features/accessPackageApi.ts
Labels: kind/feature-request

#1341 Add endpoints to GET customers
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IRegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/MockSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Enums/CustomerRoleType.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Register/CustomerList.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Register/PartyRecord.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/AgentDelegationPartyFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/forretningsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/regnskapsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/revisorCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RegisterClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserAgentDelegationControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/forretningsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/regnskapsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/revisorCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserAgentDelegationController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Test.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
Labels: kind/feature-request

#1344 Serialize access packages in systemuser object
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ResourceHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Register/CustomerList.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/SystemUser.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemRegisterService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserChangeRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/agentSystemUsers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/systemUsers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/agentSystemUser.json
Labels: kind/bug, bugfix

#1343 Feilhåndtering ved delegering / sletting av roller
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/DelegationCheck/5eb07bdc-5c3c-4c85-add3-5405b214b8a3.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/RevokeDelegation/eiendom_kjop.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/UserAccesses/cd35779b-b174-4ecc-bbef-ece13611be7f_167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Roles/GetRolesForUser/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/AccessPackageClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/AccessPackageControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/PackageDelegationCheck_returns_list.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/Role/GetRolesForUser/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  src/features/amUI/common/DelegationModal/DelegationModal.tsx
  src/features/amUI/common/DelegationModal/DelegationModalContent.tsx
  src/features/amUI/common/DelegationModal/EditModal.tsx
  src/features/amUI/common/DelegationModal/Role/RoleInfo.tsx
  src/features/amUI/common/RoleList/DelegateRoleButton.tsx
  src/features/amUI/common/RoleList/RevokeRoleButton.tsx
  src/features/amUI/common/RoleList/RoleInfoModal.tsx
  src/features/amUI/common/RoleList/RoleList.tsx
  src/features/amUI/reporteeRightsPage/ReporteeAccessPackageSection.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRightsPage.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRoleSection.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageInfoModal.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/ActiveDelegations.tsx
  src/features/amUI/userRightsPage/RoleSection/RoleSection.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightItem.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
Labels: kind/chore

#1346 Add systemuser type + fix url to get specific agent systemuser
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/SystemUserFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/SystemUser.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserClient.cs
Labels: kind/bug, bugfix

#1342 Add frontend for system user agent delegation
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/CustomerList.module.css
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/CustomerList.tsx
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPage.module.css
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPage.tsx
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPageContent.tsx
  src/features/amUI/systemUser/SystemUserDetailPage/SystemUserDetailsPage.tsx
  src/features/amUI/systemUser/SystemUsersOverviewPage/SystemUserOverviewPage.module.css
  src/features/amUI/systemUser/SystemUsersOverviewPage/SystemUserOverviewPage.test.tsx
  src/features/amUI/systemUser/SystemUsersOverviewPage/SystemUserOverviewPage.tsx
  src/features/amUI/systemUser/components/DeleteSystemUserPopover/DeleteSystemUserPopover.tsx
  src/features/amUI/systemUser/types.ts
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/routes/Router/Router.tsx
  src/routes/paths/systemUserPath.ts
  src/rtk/features/systemUserApi.ts
Labels: kind/feature-request

#1345 Context for storing FROM, TO and SELF
  .mock/handlers/lookup.ts
  .mock/handlers/singleright.ts
  .storybook/preview.tsx
  src/features/amUI/common/AccessPackageList/AccessPackageList.stories.tsx
  src/features/amUI/common/AccessPackageList/AccessPackageList.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/PackageSearch.tsx
  src/features/amUI/common/DelegationModal/DelegationModal.stories.tsx
  src/features/amUI/common/DelegationModal/DelegationModal.tsx
  src/features/amUI/common/DelegationModal/DelegationModalContent.tsx
  src/features/amUI/common/DelegationModal/EditModal.tsx
  src/features/amUI/common/DelegationModal/Role/RoleInfo.tsx
  src/features/amUI/common/DelegationModal/SingleRights/ResourceInfo.tsx
  src/features/amUI/common/PartyRepresentationContext/PartyRepresentationContext.tsx
  src/features/amUI/common/RoleList/RoleInfoModal.tsx
  src/features/amUI/common/UserList/UserListItem.tsx
  src/features/amUI/reporteeRightsPage/ReporteeAccessPackageSection.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRightsPage.tsx
  src/features/amUI/reporteeRightsPage/ReporteeRoleSection.tsx
  src/features/amUI/reporteeRightsPage/RoleInfoModal.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageInfoModal.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/AccessPackageSection.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/ActiveDelegations.tsx
  src/features/amUI/userRightsPage/RoleSection/RoleSection.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightItem.tsx
  src/features/amUI/userRightsPage/SingleRightsSection/SingleRightsSection.tsx
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/rtk/features/userInfoApi.ts
Labels: kind/chore

#1352 Add configuration for CodeRabbit settings
  .coderabbit.yaml
Labels: kind/chore

#1349 Set redirect url logout cookie for agent request
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserAgentRequestController.cs
Labels: kind/bug, bugfix

#1347 Add endpoints for customer delegation to agent systemuser
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserAgentDelegationClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/AgentDelegation.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/AgentDelegationRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/AgentDelegationFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/AgentDelegationPartyFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserAgentDelegationClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Parties/revisorCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/agentSystemUsers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/forretningsforerAgentDelegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/regnskapsforerAgentDelegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/revisorAgentDelegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserAgentDelegationClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserAgentDelegationControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/agentSystemUsers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/forretningsforerAgentDelegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/forretningsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/regnskapsforerAgentDelegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/regnskapsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/revisorAgentDelegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/revisorCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserAgentDelegationController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/CustomerList.tsx
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPageContent.tsx
  src/features/amUI/systemUser/types.ts
  src/rtk/features/systemUserApi.ts
Labels: kind/feature-request

#1357 Connect systemuser to access package metadata API
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ResourceHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemRegisterService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserChangeRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/agentSystemUser.json
Labels: kind/bug, bugfix

#1358 Map access packages for agent request
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/SystemUserAgentRequestFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemRegister/systems.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/systemUserAgentRequest.json
Labels: kind/bug, bugfix

#1362 Update DTO and request data for GET agent delegations
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserAgentDelegationClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/AgentDelegation.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/AgentDelegationFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserAgentDelegationClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/regnskapsforerAgentDelegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/revisorAgentDelegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserAgentDelegationClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserAgentDelegationControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/regnskapsforerAgentDelegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/revisorAgentDelegations.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserAgentDelegationController.cs
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPage.tsx
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPageContent.tsx
  src/features/amUI/systemUser/types.ts
  src/rtk/features/systemUserApi.ts
Labels: kind/feature-request

#1366 Update agent delegation urls
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserAgentDelegationClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserAgentDelegationClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserAgentDelegationClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserAgentDelegationControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserAgentDelegationController.cs
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPageContent.tsx
  src/rtk/features/systemUserApi.ts
Labels: kind/bug, bugfix

#1368 Include partyId in url to delete system user agent delegation
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserAgentDelegationClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserAgentDelegationClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserAgentDelegationClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserAgentDelegationController.cs
Labels: kind/bug, bugfix

#1370 Add endpoint for delete agent system user
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserController.cs
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPageContent.tsx
  src/rtk/features/systemUserApi.ts
Labels: kind/feature-request

#1371 Fixed failing test which was failing due to altinn app close button
  playwright/pages/profile/delegationPage.ts
Labels: Test

#1374 Handle response without JSON from delete delegation
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserAgentDelegationClient.cs
Labels: kind/bug, bugfix

#1376 Fix error message
  src/features/singleRight/components/ResourceActionBar/ResourceActionBar.module.css
  src/features/singleRight/components/ResourceActionBar/ResourceActionBar.tsx
Labels: kind/bug, bugfix
