Repository Altinn/altinn-access-management-frontend, pull requests merged in 2025-06, with the labels that each got.

#1459 Added missing endpoint urls
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT21.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT23.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT24.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Prod.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.TT02.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.YT01.json
Labels: kind/bug, bugfix

#1462 Include "access" property in agent delegation
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/AgentDelegationRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/ClientRoleAccessPackages.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Customer.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/AgentDelegationRequestFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/CustomerPartyFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentDelegationService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/forretningsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/regnskapsforerCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/revisorCustomers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserAgentDelegationControllerTest.cs
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/CustomerList.tsx
  src/features/amUI/systemUser/SystemUserAgentDelegationPage/SystemUserAgentDelegationPageContent.tsx
  src/features/amUI/systemUser/types.ts
  src/rtk/features/systemUserApi.ts
Labels: kind/feature-request

#1464 Added cascading delete on revoke of rightholder and chenged rightholder cashing
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RightHolderClient.cs
  src/rtk/features/userInfoApi.ts
  yarn.lock
Labels: kind/bug, bugfix

#1476 Fix hook call order when changing viewport size
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/features/amUI/common/PageLayoutWrapper/SidebarItems.tsx
Labels: kind/bug, bugfix

#1465 Remove partyId from route to GET systemuser request
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserAgentRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/SystemUserAgentRequestFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/SystemUserRequestFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/SystemUserAgentRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/SystemUserRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserAgentRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserAgentRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserAgentRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/systemUserAgentRequest.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/systemUserRequest.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserAgentRequestClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserRequestClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserAgentRequestControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserRequestControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/systemUserAgentRequest.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/systemUserRequest.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserAgentRequestController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserRequestController.cs
  src/features/amUI/systemUser/SystemUserAgentRequestPage.tsx
  src/features/amUI/systemUser/SystemUserChangeRequestPage.tsx
  src/features/amUI/systemUser/SystemUserRequestPage.tsx
  src/features/amUI/systemUser/components/RequestPageBase/RequestPageBase.tsx
  src/features/amUI/systemUser/types.ts
  src/rtk/features/systemUserApi.ts
Labels: kind/chore

#1482 Display reportee's avatar in left menu and prompt for new user on empty user list
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/features/amUI/common/PageLayoutWrapper/SidebarItems.tsx
  src/features/amUI/common/UserList/UserList.module.css
  src/features/amUI/common/UserList/UserList.tsx
  src/features/amUI/users/NewUserModal/NewUserModal.module.css
  src/features/amUI/users/NewUserModal/NewUserModal.tsx
  src/features/amUI/users/UsersList.module.css
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/feature-request

#1466 Fix systemuser typos
  src/features/amUI/systemUser/components/DelegationCheckError/DelegationCheckError.tsx
  src/features/amUI/systemUser/urlUtils.ts
  src/localizations/en.json
Labels: kind/bug, bugfix

#1488 Set cache time for assigned customers to 0
  src/rtk/features/systemUserApi.ts
Labels: kind/bug, bugfix

#1485 Fix/amui/709 update rightholders data model
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/Connection/AllowedKeysDictionaryConverter.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/Connection/Connection.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/Connection/ConnectionMapper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/Connection/Entity.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/Connection/PartyInfo.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/User/Connection/RoleInfo.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/UserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/60fb3d5b-99c2-4df0-aa77-f3fca3bc5199.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/cd35779b-b174-4ecc-bbef-ece13611be7f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/RightHolders/60fb3d5b-99c2-4df0-aa77-f3fca3bc5199.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/RightHolders/cd35779b-b174-4ecc-bbef-ece13611be7f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  src/features/amUI/common/CurrentUserPageHeader/CurrentUserPageHeader.tsx
  src/features/amUI/common/DelegationModal/Role/RoleInfo.tsx
  src/features/amUI/common/OldRolesAlert/OldRolesAlert.stories.tsx
  src/features/amUI/common/UserList/ListWrapper.tsx
  src/features/amUI/common/UserList/UserList.tsx
  src/features/amUI/common/UserList/UserListItem.tsx
  src/features/amUI/common/UserList/useFilteredUsers.test.ts
  src/features/amUI/common/UserList/useFilteredUsers.ts
  src/features/amUI/common/UserRoles/roleUtils.ts
  src/features/amUI/reportees/ReporteesList.tsx
  src/features/amUI/users/UsersList.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/userInfoApi.ts
Labels: kind/bug, bugfix

#1492 Fixed wrong defaulting for acting party
  src/features/amUI/common/AccessPackageList/AccessPackageList.tsx
  src/features/amUI/common/PartyRepresentationContext/PartyRepresentationContext.tsx
Labels: kind/bug, bugfix

#1479 use feature-toggle to disable delegation-check
  src/features/amUI/common/AccessPackageList/AreaItemContent.tsx
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/resources/hooks/useAccessPackageDelegationCheck.ts
Labels: kind/bug, bugfix

#1493 Return null instead of empty list on GET systemuser error to show error message in UI
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserClient.cs
Labels: kind/bug, bugfix

#1499 Cosmetic update and fix inherit-from message bug
  src/features/amUI/common/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/common/DelegationModal/StatusSection.module.css
  src/features/amUI/common/DelegationModal/StatusSection.tsx
Labels: kind/bug, bugfix

#1502 Fix deserialization of access package resource resourceType
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ResourceHelper.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessPackage/ResourceAM.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/packages.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/Search/emptySearch.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
Labels: kind/bug, bugfix

#1505 Add consent resource type
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Enums/ResourceType.cs
Labels: kind/bug, bugfix
