Repository Altinn/altinn-access-management-frontend, pull requests merged in 2025-01, with the labels that each got.

#1200 Update to .net 9
  .github/workflows/codeql.yml
  .github/workflows/template-build-and-test-backend.yml
  .mock/mockServiceWorker.js
  .yarn/releases/yarn-4.6.0.cjs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Altinn.AccessManagement.UI.Core.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/AccessTokenProvider.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Altinn.AccessManagement.UI.Integration.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Altinn.AccessManagement.UI.Mocks.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/ConfigurationManagerStub.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Utils/JwtTokenMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Altinn.AccessManagement.UI.Tests.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Dockerfile
Labels: kind/chore

#1205 Fixed one test which was failing in tt02
  .github/workflows/deploy-at.yml
  playwright/e2eTests/api-delegering.spec.ts
  playwright/pages/profile/apidelegeringPage.ts
Labels: Test

#1206 Docekrfil to .net9
  Dockerfile
Labels: kind/chore

#1208 Refactor Dockerfile to streamline build process
  Dockerfile
Labels: kind/chore

#1217 Chore: upgrade StyleCop.Analyzers package
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Altinn.AccessManagement.UI.Core.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/Common/HttpErrorResponse.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Altinn.AccessManagement.UI.Integration.csproj
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.csproj
Labels: kind/chore

#1215 Chore: move systemregister from altinn-authentication-frontend repo
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IRegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemRegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Configuration/MockSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Helpers/ResourceUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/RegisteredSystem.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemRegisterService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemRegisterService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemRegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/ResourceRegistry/resources.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemRegister/systems.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RegisterClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemRegisterClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemRegisterControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemRegister/allSystems.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemRegister/systemRights.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemRegisterController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.AT22.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Test.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
Labels: kind/chore

#1220 Add new person as user in organization
  .mock/handlers/user.ts
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/IRegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/IUserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/UserService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/ClientUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/RegisterClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/ebd192ea-753b-448e-9226-95e8c439bd9f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Persons/19895199357.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Persons/20838198385.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Register/Persons/21915399719.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/RightHolderAccess/ebd192ea-753b-448e-9226-95e8c439bd9f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/RegisterClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Models/ValidatePersonInput.cs
  src/features/amUI/users/NewUserModal/NewPersonContent.tsx
  src/features/amUI/users/NewUserModal/NewUserAlert.tsx
  src/features/amUI/users/NewUserModal/NewUserModal.module.css
  src/features/amUI/users/NewUserModal/NewUserModal.stories.tsx
  src/features/amUI/users/NewUserModal/NewUserModal.tsx
  src/features/amUI/users/UsersList.module.css
  src/features/amUI/users/UsersList.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/userInfoApi.ts
Labels: kind/feature-request

#1227 Remove deploy to AT21
  .github/workflows/deploy-at.yml
Labels: kind/chore

#1232 Feat/am UI/195 add new user org
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/UserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/UserController.cs
  src/features/amUI/common/TechnicalErrorParagraphs/TechnicalErrorParagraph.stories.tsx
  src/features/amUI/common/TechnicalErrorParagraphs/TechnicalErrorParagraphs.tsx
  src/features/amUI/common/TechnicalErrorParagraphs/index.ts
  src/features/amUI/userRightsPage/DelegationModal/SingleRights/ResourceAlert.tsx
  src/features/amUI/userRightsPage/DelegationModal/SingleRights/ResourceInfo.tsx
  src/features/amUI/users/NewUserModal/NewOrgContent.tsx
  src/features/amUI/users/NewUserModal/NewPersonContent.tsx
  src/features/amUI/users/NewUserModal/NewUserAlert.tsx
  src/features/amUI/users/NewUserModal/NewUserModal.module.css
  src/features/amUI/users/NewUserModal/NewUserModal.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/rtk/features/lookupApi.ts
  src/rtk/features/userInfoApi.ts
Labels: kind/feature-request

#1233 Vise Digdir-roller "Administratortilganger" fanen
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/AccessManagement/RightHolderAccesses.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/RightHolderAccess/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/RightHolderAccess/26ca8b02-c455-4dc0-96be-f92864837ff9.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/RightHolderAccess/5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/RightHolders/RightHolderAccess/ebd192ea-753b-448e-9226-95e8c439bd9f.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Roles/GetRolesForUser/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Roles/GetRolesForUser/26ca8b02-c455-4dc0-96be-f92864837ff9.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/Roles/GetRolesForUser/5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/RoleControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/Role/GetRolesForUser/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/Role/GetRolesForUser/26ca8b02-c455-4dc0-96be-f92864837ff9.json
  src/features/amUI/common/UserRoles/UserRoles.tsx
  src/features/amUI/userRightsPage/RoleSection/RoleSection.tsx
  src/features/amUI/userRightsPage/RoleSection/roleSection.module.css
  src/features/amUI/userRightsPage/UserRightsPage.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
  src/resources/utils/roleUtils.ts
  src/rtk/app/store.ts
  src/rtk/features/userInfoApi.ts
Labels: kind/feature-request

#1234 Cosmetic changes to UI
  src/features/amUI/common/ButtonWithConfirmPopup/ButtonWithConfirmPopup.module.css
  src/features/amUI/common/ButtonWithConfirmPopup/ButtonWithConfirmPopup.tsx
  src/features/amUI/common/PageContainer/PageContainer.module.css
  src/features/amUI/common/PageLayoutWrapper/PageLayoutWrapper.tsx
  src/features/amUI/userRightsPage/AccessPackageSection/DeletePackageButton.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.module.css
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/DelegationModalContent.tsx
  src/features/amUI/userRightsPage/DelegationModal/SingleRights/ResourceInfo.module.css
  src/features/amUI/userRightsPage/SingleRightsSection/DeleteResourceButton.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/chore

#1243 Add more realistick mock data for demo purposes
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/AccessPackageClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Configuration/PlatformSettings.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/GetDelegations/5c0656db-cf51-43a4-bd64-6a91c8caacfb.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/AccessPackage/packages.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/AccessPackageControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/GetDelegations/167536b5-f8ed-4c5a-8f48-0279507e53ae.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/Search/emptySearch.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/AccessPackage/Search/searchString_a.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.Development.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/appsettings.json
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.module.css
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/AccessPackageInfo.tsx
  src/features/amUI/userRightsPage/DelegationModal/AccessPackages/PackageSearch.module.css
Labels: kind/feature-request

#1244 Add cors origin
  vite.config.ts
Labels: kind/chore

#1245 Enhance cookie security by adding SameSite attribute to cookie
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/HomeController.cs
Labels: kind/chore

#1247 Test/general/1204 add playwright accessibility tests
  .github/workflows/deploy-at.yml
  .github/workflows/deploy-release.yml
  .gitignore
  playwright/config/.env.at22
  playwright/fixture/pomFixture.ts
  playwright/pages/profile/brukerflateDelegtionPage.ts
  playwright/playwright.config.ts
  playwright/uuTests/accessibilityHelpers/delegeringHelper.spec.ts
  playwright/uuTests/accessibilityTests/enkelttjenesteDelegering.spec.ts
Labels: Test

#1231 Move controller, service and client for system user request
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/ClientInterfaces/ISystemUserRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/Frontend/SystemUserRequestFE.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Models/SystemUser/SystemUserRequest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/Interfaces/ISystemUserRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Core/Services/SystemUserRequestService.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Integration/Clients/SystemUserRequestClient.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Data/SystemUser/systemUserRequest.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemRegisterClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Mocks/Mocks/SystemUserRequestClientMock.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemRegisterControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Controllers/SystemUserRequestControllerTest.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/systemUserRequest.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Data/ExpectedResults/SystemUser/systemUsers.json
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/AssertionUtil.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI.Tests/Utils/SetupUtils.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Controllers/SystemUserRequestController.cs
  backend/src/Altinn.AccessManagement.UI/Altinn.AccessManagement.UI/Program.cs
Labels: kind/chore

#1248 Fix formatting on dete resource snackbar
  src/features/amUI/userRightsPage/SingleRightsSection/DeleteResourceButton.tsx
  src/localizations/en.json
  src/localizations/no_nb.json
  src/localizations/no_nn.json
Labels: kind/bug, bugfix

#1250 Added package which is required to run accessibility tests
  package.json
  yarn.lock
Labels: Test

#1253 Made TT02 and PROD env names uppercase in deploy workflow
  .github/workflows/deploy-release.yml
Labels: kind/chore
